import React,{createContext,useCallback,useContext,useEffect,useState} from 'react';
import {Check,AlertTriangle,Info,X,LoaderCircle} from 'lucide-react';
import {Link} from 'react-router-dom';

const ToastContext=createContext(()=>{});
export function ToastProvider({children}){
 const [items,setItems]=useState([]);const push=useCallback((message,type='success')=>{const id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;setItems(list=>[...list,{id,message,type}]);setTimeout(()=>setItems(list=>list.filter(x=>x.id!==id)),3600);},[]);
 return <ToastContext.Provider value={push}>{children}<div className="toast-stack" aria-live="polite">{items.map(t=><div key={t.id} className={`toast toast-${t.type}`}>{t.type==='error'?<AlertTriangle size={18}/>:t.type==='info'?<Info size={18}/>:<Check size={18}/>}<span>{t.message}</span><button className="icon-btn tiny" onClick={()=>setItems(list=>list.filter(x=>x.id!==t.id))} aria-label="إغلاق"><X size={15}/></button></div>)}</div></ToastContext.Provider>;
}
export const useToast=()=>useContext(ToastContext);

export function Button({children,variant='primary',size='md',loading=false,icon:Icon,disabled=false,className='',...props}){return <button className={`btn btn-${variant} btn-${size} ${className}`} disabled={disabled||loading} {...props}>{loading?<LoaderCircle size={16} className="spin"/>:Icon?<Icon size={16}/>:null}<span>{children}</span></button>;}
export function IconButton({icon:Icon,label,onClick,className='',...props}){return <button type="button" className={`icon-btn ${className}`} aria-label={label} title={label} onClick={onClick} {...props}><Icon size={18}/></button>;}
export function Card({children,className='',...props}){return <section className={`card ${className}`} {...props}>{children}</section>;}
export function PageHeading({title,eyebrow,description,actions}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</div>;}
export function StatCard({label,value,icon:Icon,caption,tone='teal'}){return <Card className={`stat-card tone-${tone}`}><div className="stat-top"><span>{label}</span><span className="stat-icon"><Icon size={19}/></span></div><strong>{value??'—'}</strong>{caption&&<small>{caption}</small>}</Card>;}
export function Badge({children,tone='neutral'}){return <span className={`badge badge-${tone}`}>{children}</span>;}
export function StatusBadge({status}){const map={active:['نشط','success'],confirmed:['مؤكد','success'],pending:['قيد الانتظار','warning'],checked_in:['تم الوصول','info'],in_progress:['جارٍ الكشف','info'],completed:['مكتمل','neutral'],cancelled:['ملغي','danger'],no_show:['لم يحضر','danger'],waiting:['في الانتظار','warning'],called:['تم النداء','info'],in_visit:['داخل الكشف','teal'],done:['منتهٍ','neutral'],skipped:['تم التخطي','neutral'],new:['جديد','info'],sample_collected:['تم سحب العينة','warning'],result_ready:['النتيجة جاهزة','success'],reviewed:['تمت المراجعة','success'],draft:['مسودة','warning'],active_rx:['نشطة','success'],expired:['منتهية','neutral'],unpaid:['غير مدفوعة','danger'],partial:['مدفوعة جزئيًا','warning'],paid:['مدفوعة','success'],void:['ملغاة','neutral'],suspended:['موقوف','danger']};const [text,tone]=map[status]||[status||'غير محدد','neutral'];return <Badge tone={tone}>{text}</Badge>;}
export function Modal({open,onClose,title,children,footer,width='md'}){useEffect(()=>{if(!open)return;const onKey=e=>e.key==='Escape'&&onClose?.();document.addEventListener('keydown',onKey);document.body.classList.add('modal-open');return()=>{document.removeEventListener('keydown',onKey);document.body.classList.remove('modal-open');};},[open,onClose]);if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose?.()}><div className={`modal modal-${width}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><div><h2>{title}</h2></div><button className="icon-btn" onClick={onClose} aria-label="إغلاق"><X size={19}/></button></div><div className="modal-content">{children}</div>{footer&&<div className="modal-footer">{footer}</div>}</div></div>;}
export function EmptyState({icon:Icon,title,description,action}){return <div className="empty-state">{Icon&&<span className="empty-icon"><Icon size={24}/></span>}<h3>{title||'لا توجد بيانات بعد'}</h3>{description&&<p>{description}</p>}{action}</div>;}
export function Field({label,required,help,error,children,className=''}){return <label className={`field ${className}`}><span className="field-label">{label}{required&&<b className="required">*</b>}</span>{children}{help&&<small className="field-help">{help}</small>}{error&&<small className="field-error">{error}</small>}</label>;}
export function Input({icon:Icon,className='',...props}){return <span className={`input-wrap ${className}`}>{Icon&&<Icon size={17} className="input-icon"/>}<input className="input" {...props}/></span>;}
export function Select({children,className='',...props}){return <select className={`input select ${className}`} {...props}>{children}</select>;}
export function Textarea({className='',...props}){return <textarea className={`input textarea ${className}`} {...props}/>;}
export function Toggle({checked,onChange,label,disabled=false}){return <label className={`toggle-row ${disabled?'is-disabled':''}`}><span>{label}</span><button type="button" className={`toggle ${checked?'on':''}`} role="switch" aria-checked={checked} disabled={disabled} onClick={()=>onChange(!checked)}><i/></button></label>;}
export function ConfirmDialog({open,title='تأكيد الإجراء',message,onCancel,onConfirm,confirmLabel='تأكيد',danger=false,loading=false}){return <Modal open={open} onClose={onCancel} title={title} width="sm" footer={<><Button variant="ghost" onClick={onCancel}>إلغاء</Button><Button variant={danger?'danger':'primary'} onClick={onConfirm} loading={loading}>{confirmLabel}</Button></>}><p className="confirm-copy">{message}</p></Modal>;}
export function Breadcrumb({items=[]}){return <nav className="breadcrumbs">{items.map((x,i)=><React.Fragment key={x.label}>{i>0&&<span>/</span>}{x.to?<Link to={x.to}>{x.label}</Link>:<b>{x.label}</b>}</React.Fragment>)}</nav>;}
