const timestamp = (table, column, knex) => knex.client.config.client === 'pg'
  ? table.timestamp(column, { useTz: true })
  : table.timestamp(column);

const ts = (table, knex) => {
  timestamp(table, 'created_at', knex).notNullable().defaultTo(knex.fn.now());
  timestamp(table, 'updated_at', knex).notNullable().defaultTo(knex.fn.now());
};

export async function up(knex) {
  await knex.schema.createTable('clinics', (t) => {
    t.bigIncrements('id').primary(); t.string('name', 180).notNullable(); t.string('logo_path', 512); t.string('phone', 32); t.string('email', 190); t.string('address', 500); t.decimal('consultation_fee', 12, 2).notNullable().defaultTo(0); t.string('timezone', 64).notNullable().defaultTo('Africa/Cairo'); t.string('currency', 8).notNullable().defaultTo('EGP'); t.decimal('tax_percent', 5, 2).notNullable().defaultTo(0); ts(t, knex);
  });
  await knex.schema.createTable('users', (t) => {
    t.bigIncrements('id').primary(); t.bigInteger('clinic_id').unsigned().references('id').inTable('clinics').onDelete('CASCADE'); t.enu('role', ['admin','doctor','receptionist','patient']).notNullable(); t.string('full_name', 180).notNullable(); t.string('email', 190).nullable().unique(); t.string('phone', 32).nullable().unique(); t.string('password_hash', 255).notNullable(); t.enu('status', ['active','suspended']).notNullable().defaultTo('active'); t.boolean('must_change_password').notNullable().defaultTo(false); timestamp(t, 'last_login_at', knex); t.integer('failed_logins').notNullable().defaultTo(0); timestamp(t, 'locked_until', knex); t.string('avatar_path', 512); t.string('language', 8).notNullable().defaultTo('ar'); t.string('theme', 12).notNullable().defaultTo('light'); timestamp(t, 'deleted_at', knex); ts(t, knex); t.index(['clinic_id','role']); t.index('full_name');
  });
  await knex.schema.createTable('refresh_tokens', (t) => { t.bigIncrements('id').primary(); t.bigInteger('user_id').unsigned().notNullable().references('id').inTable('users').onDelete('CASCADE'); t.string('token_hash', 128).notNullable().unique(); t.string('user_agent', 512); t.string('ip', 64); timestamp(t, 'expires_at', knex).notNullable(); timestamp(t, 'revoked_at', knex); timestamp(t, 'last_used_at', knex); ts(t, knex); });
  await knex.schema.createTable('role_permissions', (t) => { t.bigIncrements('id').primary(); t.string('role', 32).notNullable(); t.string('permission_key', 96).notNullable(); t.boolean('allowed').notNullable().defaultTo(false); ts(t, knex); t.unique(['role','permission_key']); });
  await knex.schema.createTable('doctor_profiles', (t) => { t.bigIncrements('id').primary(); t.bigInteger('user_id').unsigned().notNullable().unique().references('id').inTable('users').onDelete('CASCADE'); t.string('specialty', 160); t.text('bio'); t.integer('avg_visit_minutes').notNullable().defaultTo(15); t.bigInteger('clinic_id').unsigned().references('id').inTable('clinics'); ts(t, knex); });
  await knex.schema.createTable('working_hours', (t) => { t.bigIncrements('id').primary(); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users').onDelete('CASCADE'); t.integer('weekday').notNullable(); t.boolean('is_open').notNullable().defaultTo(true); t.string('start_time', 5).notNullable().defaultTo('09:00'); t.string('end_time', 5).notNullable().defaultTo('17:00'); t.unique(['doctor_id','weekday']); });
  await knex.schema.createTable('patients', (t) => { t.bigIncrements('id').primary(); t.bigInteger('clinic_id').unsigned().references('id').inTable('clinics'); t.bigInteger('user_id').unsigned().nullable().unique().references('id').inTable('users').onDelete('SET NULL'); t.string('file_no', 40).notNullable().unique(); t.string('first_name', 100).notNullable(); t.string('last_name', 100).notNullable(); t.date('dob'); t.enu('sex', ['female','male','unspecified']).notNullable().defaultTo('unspecified'); t.string('phone', 32); t.string('email', 190); t.string('address', 500); t.string('emergency_contact_name', 160); t.string('emergency_contact_phone', 32); t.text('national_id_enc'); t.string('national_id_last4', 4); t.enu('status', ['active','pending','archived']).notNullable().defaultTo('active'); timestamp(t, 'deleted_at', knex); ts(t, knex); t.index(['first_name','last_name']); t.index('phone'); });
  await knex.schema.createTable('patient_medical', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().unique().references('id').inTable('patients').onDelete('CASCADE'); t.text('allergies'); t.text('chronic_conditions'); t.text('current_medications'); t.text('initial_notes'); t.boolean('allergy_flag').notNullable().defaultTo(false); ts(t, knex); });
  await knex.schema.createTable('services', (t) => { t.bigIncrements('id').primary(); t.bigInteger('clinic_id').unsigned().references('id').inTable('clinics'); t.string('name', 180).notNullable(); t.decimal('price', 12, 2).notNullable().defaultTo(0); t.integer('duration_minutes').notNullable().defaultTo(15); t.string('color', 16).notNullable().defaultTo('#0F7778'); t.boolean('is_active').notNullable().defaultTo(true); ts(t, knex); });
  await knex.schema.createTable('appointments', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users'); t.bigInteger('service_id').unsigned().references('id').inTable('services'); t.enu('type', ['first','follow_up','consultation','lab']).notNullable().defaultTo('first'); timestamp(t, 'start_at', knex).notNullable(); timestamp(t, 'end_at', knex).notNullable(); t.string('reason', 500); t.text('notes'); t.enu('status', ['pending','confirmed','checked_in','in_progress','completed','cancelled','no_show']).notNullable().defaultTo('confirmed'); t.bigInteger('created_by').unsigned().references('id').inTable('users'); t.bigInteger('cancelled_by').unsigned().references('id').inTable('users'); timestamp(t, 'cancelled_at', knex); ts(t, knex); t.index(['doctor_id','start_at']); t.index(['patient_id','start_at']); });
  await knex.schema.createTable('queue_entries', (t) => { t.bigIncrements('id').primary(); t.date('queue_date').notNullable(); t.integer('number').notNullable(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('appointment_id').unsigned().nullable().references('id').inTable('appointments'); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users'); t.enu('status', ['waiting','called','in_visit','done','skipped','removed']).notNullable().defaultTo('waiting'); timestamp(t, 'arrived_at', knex).notNullable().defaultTo(knex.fn.now()); timestamp(t, 'called_at', knex); timestamp(t, 'finished_at', knex); ts(t, knex); t.unique(['doctor_id','queue_date','number']); t.index(['doctor_id','queue_date','status']); });
  await knex.schema.createTable('visits', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users'); t.bigInteger('appointment_id').unsigned().nullable().references('id').inTable('appointments'); t.string('type', 32).notNullable().defaultTo('first'); t.text('complaint'); t.text('examination'); t.text('diagnosis'); t.enu('status',['draft','signed']).notNullable().defaultTo('draft'); timestamp(t, 'signed_at', knex); ts(t, knex); });
  await knex.schema.createTable('notes', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('visit_id').unsigned().nullable().references('id').inTable('visits'); t.bigInteger('author_id').unsigned().notNullable().references('id').inTable('users'); t.string('title', 180); t.text('body'); t.boolean('has_audio').notNullable().defaultTo(false); ts(t, knex); });
  await knex.schema.createTable('medications', (t) => { t.bigIncrements('id').primary(); t.string('name_ar', 180).notNullable(); t.string('name_en', 180); t.string('brand', 180); t.string('class', 120); t.text('common_doses'); t.boolean('is_active').notNullable().defaultTo(true); ts(t, knex); });
  await knex.schema.createTable('prescriptions', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users'); t.bigInteger('visit_id').unsigned().nullable().references('id').inTable('visits'); t.text('diagnosis'); t.text('recommendations'); t.enu('status',['draft','active','expired','amended']).notNullable().defaultTo('active'); timestamp(t, 'issued_at', knex).notNullable().defaultTo(knex.fn.now()); t.bigInteger('amends_id').unsigned().nullable().references('id').inTable('prescriptions'); ts(t, knex); });
  await knex.schema.createTable('prescription_items', (t) => { t.bigIncrements('id').primary(); t.bigInteger('prescription_id').unsigned().notNullable().references('id').inTable('prescriptions').onDelete('CASCADE'); t.bigInteger('medication_id').unsigned().nullable().references('id').inTable('medications'); t.string('name_snapshot', 180).notNullable(); t.string('dose', 120); t.string('frequency', 160); t.string('route', 64); t.string('duration', 100); t.text('instructions'); });
  await knex.schema.createTable('lab_tests', (t) => { t.bigIncrements('id').primary(); t.string('name_ar', 180).notNullable(); t.string('name_en', 180); t.string('category', 120); t.string('unit', 40); t.decimal('ref_min', 12, 3); t.decimal('ref_max', 12, 3); t.string('ref_text', 160); t.decimal('price', 12, 2).notNullable().defaultTo(0); t.integer('turnaround_hours').notNullable().defaultTo(24); t.boolean('is_active').notNullable().defaultTo(true); ts(t, knex); });
  await knex.schema.createTable('lab_orders', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users'); t.bigInteger('visit_id').unsigned().nullable().references('id').inTable('visits'); t.enu('priority',['normal','urgent']).notNullable().defaultTo('normal'); t.text('reason'); t.enu('status',['new','sample_collected','result_ready','reviewed']).notNullable().defaultTo('new'); timestamp(t, 'ordered_at', knex).notNullable().defaultTo(knex.fn.now()); ts(t, knex); });
  await knex.schema.createTable('lab_order_items', (t) => { t.bigIncrements('id').primary(); t.bigInteger('lab_order_id').unsigned().notNullable().references('id').inTable('lab_orders').onDelete('CASCADE'); t.bigInteger('lab_test_id').unsigned().notNullable().references('id').inTable('lab_tests'); t.decimal('price_snapshot',12,2).notNullable().defaultTo(0); t.string('value_text', 180); t.decimal('value_number',12,3); t.enu('flag',['normal','out_of_range','unknown']).notNullable().defaultTo('unknown'); t.bigInteger('file_id').unsigned(); t.bigInteger('resulted_by').unsigned().references('id').inTable('users'); timestamp(t, 'resulted_at', knex); });
  await knex.schema.createTable('invoices', (t) => { t.bigIncrements('id').primary(); t.string('number', 40).notNullable().unique(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('appointment_id').unsigned().nullable().references('id').inTable('appointments'); t.decimal('subtotal',12,2).notNullable().defaultTo(0); t.decimal('tax_amount',12,2).notNullable().defaultTo(0); t.decimal('total',12,2).notNullable().defaultTo(0); t.decimal('paid_amount',12,2).notNullable().defaultTo(0); t.enu('status',['unpaid','partial','paid','void']).notNullable().defaultTo('unpaid'); timestamp(t, 'issued_at', knex).notNullable().defaultTo(knex.fn.now()); timestamp(t, 'due_at', knex); t.text('void_reason'); ts(t, knex); });
  await knex.schema.createTable('invoice_items', (t) => { t.bigIncrements('id').primary(); t.bigInteger('invoice_id').unsigned().notNullable().references('id').inTable('invoices').onDelete('CASCADE'); t.string('description', 240).notNullable(); t.integer('quantity').notNullable().defaultTo(1); t.decimal('unit_price',12,2).notNullable().defaultTo(0); });
  await knex.schema.createTable('payments', (t) => { t.bigIncrements('id').primary(); t.bigInteger('invoice_id').unsigned().notNullable().references('id').inTable('invoices'); t.decimal('amount',12,2).notNullable(); t.enu('method',['cash','card','wallet']).notNullable().defaultTo('cash'); timestamp(t, 'paid_at', knex).notNullable().defaultTo(knex.fn.now()); t.bigInteger('received_by').unsigned().notNullable().references('id').inTable('users'); t.string('reference', 120); ts(t, knex); });
  await knex.schema.createTable('message_threads', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.string('subject',180); t.enu('status',['open','closed','reported']).notNullable().defaultTo('open'); ts(t, knex); });
  await knex.schema.createTable('messages', (t) => { t.bigIncrements('id').primary(); t.bigInteger('thread_id').unsigned().notNullable().references('id').inTable('message_threads').onDelete('CASCADE'); t.bigInteger('sender_id').unsigned().notNullable().references('id').inTable('users'); t.text('body'); t.bigInteger('file_id').unsigned(); timestamp(t, 'read_at', knex); ts(t, knex); });
  await knex.schema.createTable('notifications', (t) => { t.bigIncrements('id').primary(); t.bigInteger('user_id').unsigned().notNullable().references('id').inTable('users').onDelete('CASCADE'); t.string('type', 48).notNullable().defaultTo('info'); t.string('title', 180).notNullable(); t.text('body'); t.string('link', 300); timestamp(t, 'read_at', knex); t.text('channel_status'); ts(t, knex); t.index(['user_id','read_at']); });
  await knex.schema.createTable('files', (t) => { t.bigIncrements('id').primary(); t.bigInteger('owner_id').unsigned().references('id').inTable('users'); t.bigInteger('patient_id').unsigned().references('id').inTable('patients'); t.string('path',512).notNullable(); t.string('original_name',255).notNullable(); t.string('mime',120).notNullable(); t.bigInteger('size').notNullable().defaultTo(0); t.string('kind',80); t.bigInteger('uploaded_by').unsigned().references('id').inTable('users'); ts(t, knex); });
  await knex.schema.createTable('ai_plans', (t) => { t.bigIncrements('id').primary(); t.bigInteger('patient_id').unsigned().notNullable().references('id').inTable('patients'); t.bigInteger('doctor_id').unsigned().notNullable().references('id').inTable('users'); t.text('summary'); t.text('suggestions'); t.text('decisions'); t.string('model',100); ts(t, knex); });
  await knex.schema.createTable('settings', (t) => { t.bigIncrements('id').primary(); t.string('key', 120).notNullable().unique(); t.text('value'); ts(t, knex); });
  await knex.schema.createTable('audit_logs', (t) => { t.bigIncrements('id').primary(); t.bigInteger('user_id').unsigned().nullable().references('id').inTable('users'); t.string('action',80).notNullable(); t.string('entity',80); t.string('entity_id',80); t.text('meta'); t.string('ip',64); timestamp(t, 'created_at', knex).notNullable().defaultTo(knex.fn.now()); t.index(['entity','entity_id']); t.index('created_at'); });
  await knex.schema.createTable('backups', (t) => { t.bigIncrements('id').primary(); t.string('path',512).notNullable(); t.bigInteger('size').notNullable().defaultTo(0); t.enu('status',['complete','failed']).notNullable().defaultTo('complete'); t.bigInteger('created_by').unsigned().references('id').inTable('users'); timestamp(t, 'created_at', knex).notNullable().defaultTo(knex.fn.now()); });
}

export async function down(knex) {
  for (const name of ['backups','audit_logs','settings','ai_plans','files','notifications','messages','message_threads','payments','invoice_items','invoices','lab_order_items','lab_orders','lab_tests','prescription_items','prescriptions','medications','notes','visits','queue_entries','appointments','services','patient_medical','patients','working_hours','doctor_profiles','role_permissions','refresh_tokens','users','clinics']) {
    await knex.schema.dropTableIfExists(name);
  }
}
