import { Router } from 'express';
import dayjs from 'dayjs';
import { z } from 'zod';
import { db } from '../db/knex.js';
import { insertAndGetId } from '../db/insert-id.js';
import { requireAuth, requirePermission, ensurePatientAccess } from '../middleware/auth.js';
import { asyncHandler, HttpError, idParam, pagination, pageResult } from '../utils/http.js';
import { audit, notify } from '../utils/audit.js';

const router=Router();router.use(requireAuth);
const cents=(value)=>Math.round(Number(value||0)*100);
const money=(value)=>Number((Number(value||0)).toFixed(2));
async function billingSettings(){const row=await db('settings').where({key:'settings:billing'}).first();return row?JSON.parse(row.value):{currency:'EGP',taxPercent:0,invoiceFormat:'INV-{YYYY}-{#####}',paymentMethods:['cash','card','wallet']};}

router.get('/summary',requirePermission('invoices.read'),asyncHandler(async(req,res)=>{
 let rows=db('invoices');if(req.user.role==='patient'){const patient=await db('patients').where({user_id:req.user.id}).first();rows=rows.where({patient_id:patient?.id||-1});}
 const all=await rows.clone().whereNot('status','void');const today=dayjs().format('YYYY-MM-DD');const todayInvoices=all.filter(x=>String(x.issued_at).slice(0,10)===today);const payments=await db('payments').where('paid_at','>=',`${today} 00:00:00`);const due=all.filter(x=>x.status==='unpaid'||x.status==='partial');const overdue=due.filter(x=>x.due_at&&new Date(x.due_at).getTime()<Date.now());res.json({data:{invoicesToday:todayInvoices.length,revenueToday:money(payments.reduce((a,x)=>a+Number(x.amount),0)),outstanding:money(due.reduce((a,x)=>a+Number(x.total)-Number(x.paid_amount),0)),overdueCount:overdue.length,currency:'EGP'}});
}));
router.get('/',requirePermission('invoices.read'),asyncHandler(async(req,res)=>{
 const {page,pageSize,offset}=pagination(req.query);let query=db('invoices as i').join('patients as p','i.patient_id','p.id').select('i.*','p.first_name','p.last_name','p.file_no');if(req.user.role==='patient'){const patient=await db('patients').where({user_id:req.user.id}).first();query=query.where('i.patient_id',patient?.id||-1);}if(req.query.status)query=query.where('i.status',String(req.query.status));const q=String(req.query.q||'').trim();if(q)query=query.andWhere(b=>b.where('i.number','like',`%${q}%`).orWhere('p.first_name','like',`%${q}%`).orWhere('p.last_name','like',`%${q}%`).orWhere('p.file_no','like',`%${q}%`));const count=await query.clone().clearSelect().count({count:'i.id'}).first();const rows=await query.orderBy('i.issued_at','desc').limit(pageSize).offset(offset);res.json(pageResult(rows.map(x=>({id:x.id,number:x.number,patientId:x.patient_id,patientName:`${x.first_name} ${x.last_name}`,fileNo:x.file_no,subtotal:Number(x.subtotal),taxAmount:Number(x.tax_amount),total:Number(x.total),paidAmount:Number(x.paid_amount),remaining:money(Number(x.total)-Number(x.paid_amount)),status:x.status,issuedAt:x.issued_at,dueAt:x.due_at})),Number(count.count),page,pageSize));
}));
router.post('/',requirePermission('invoices.write'),asyncHandler(async(req,res)=>{
 const input=z.object({patientId:z.coerce.number().int().positive(),appointmentId:z.coerce.number().int().positive().nullable().optional(),dueAt:z.string().optional().nullable(),items:z.array(z.object({description:z.string().trim().min(2).max(240),quantity:z.coerce.number().int().min(1).max(100),unitPrice:z.coerce.number().min(0)})).min(1)}).parse(req.body);const patient=await db('patients').where({id:input.patientId}).whereNull('deleted_at').first();if(!patient)throw new HttpError(404,'PATIENT_NOT_FOUND','المريض غير موجود.');const settings=await billingSettings();const subtotal=input.items.reduce((sum,x)=>sum+cents(x.unitPrice)*x.quantity,0)/100;const tax=money(subtotal*Number(settings.taxPercent||0)/100);const total=money(subtotal+tax);
 const id=await db.transaction(async trx=>{
  const year=dayjs().year();const like=`INV-${year}-%`;const last=await trx('invoices').where('number','like',like).orderBy('number','desc').first();const seq=last?Number(last.number.split('-').at(-1))+1:1;const number=`INV-${year}-${String(seq).padStart(5,'0')}`;
  const invoiceId=await insertAndGetId(trx('invoices').insert({number,patient_id:input.patientId,appointment_id:input.appointmentId||null,subtotal,tax_amount:tax,total,paid_amount:0,status:'unpaid',issued_at:trx.fn.now(),due_at:input.dueAt||null}));for(const item of input.items)await trx('invoice_items').insert({invoice_id:invoiceId,description:item.description,quantity:item.quantity,unit_price:item.unitPrice});return invoiceId;
 });await audit(req,'invoice.create','invoice',id,{patientId:input.patientId,total});res.status(201).json({data:await db('invoices').where({id}).first()});
}));
router.get('/:id',requirePermission('invoices.read'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const invoice=await db('invoices').where({id}).first();if(!invoice)throw new HttpError(404,'INVOICE_NOT_FOUND','الفاتورة غير موجودة.');if(req.user.role==='patient'){const patient=await db('patients').where({id:invoice.patient_id}).first();ensurePatientAccess(patient,req.user);}const [items,payments]=await Promise.all([db('invoice_items').where({invoice_id:id}),db('payments').where({invoice_id:id}).orderBy('paid_at','desc')]);await audit(req,'invoice.read','invoice',id);res.json({data:{...invoice,items,payments,remaining:money(Number(invoice.total)-Number(invoice.paid_amount))}});}));
router.post('/:id/payments',requirePermission('payments.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const input=z.object({amount:z.coerce.number().positive(),method:z.enum(['cash','card','wallet']),paidAt:z.string().optional(),reference:z.string().max(120).optional()}).parse(req.body);const result=await db.transaction(async trx=>{const invoice=await trx('invoices').where({id}).first();if(!invoice)throw new HttpError(404,'INVOICE_NOT_FOUND','الفاتورة غير موجودة.');if(invoice.status==='void')throw new HttpError(409,'INVOICE_VOID','لا يمكن تسجيل دفع على فاتورة ملغاة.');const remaining=cents(invoice.total)-cents(invoice.paid_amount);if(cents(input.amount)>remaining)throw new HttpError(422,'OVERPAYMENT',`المبلغ أكبر من الرصيد المتبقي (${(remaining/100).toFixed(2)} ج.م).`);const paymentId=await insertAndGetId(trx('payments').insert({invoice_id:id,amount:input.amount,method:input.method,paid_at:input.paidAt||trx.fn.now(),received_by:req.user.id,reference:input.reference||null}));const newPaid=money(Number(invoice.paid_amount)+Number(input.amount));const status=cents(newPaid)>=cents(invoice.total)?'paid':'partial';await trx('invoices').where({id}).update({paid_amount:newPaid,status,updated_at:trx.fn.now()});return {paymentId,invoice:await trx('invoices').where({id}).first()};});await audit(req,'invoice.payment.create','payment',result.paymentId,{invoiceId:id,amount:input.amount,method:input.method});const p=await db('patients').where({id:result.invoice.patient_id}).first();if(p?.user_id)await notify(p.user_id,'payment','تم تسجيل دفعة','تم تحديث حالة الفاتورة.','/portal/invoices');res.status(201).json({data:result.invoice,remaining:money(Number(result.invoice.total)-Number(result.invoice.paid_amount))});}));
router.post('/:id/void',requirePermission('invoices.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const input=z.object({reason:z.string().trim().min(5).max(500)}).parse(req.body);const invoice=await db('invoices').where({id}).first();if(!invoice)throw new HttpError(404,'INVOICE_NOT_FOUND','الفاتورة غير موجودة.');if(invoice.paid_amount>0)throw new HttpError(409,'INVOICE_HAS_PAYMENTS','لا يمكن إلغاء فاتورة عليها دفعات؛ راجع سجل المدفوعات.');await db('invoices').where({id}).update({status:'void',void_reason:input.reason,updated_at:db.fn.now()});await audit(req,'invoice.void','invoice',id,{reason:input.reason});res.json({message:'تم إلغاء الفاتورة مع حفظ سبب الإلغاء.'});}));

export default router;
