import { Router } from 'express';
import { z } from 'zod';
import { db } from '../db/knex.js';
import { insertAndGetId } from '../db/insert-id.js';
import { requireAuth, requirePermission, ensurePatientAccess } from '../middleware/auth.js';
import { asyncHandler, HttpError, idParam, pagination, pageResult } from '../utils/http.js';
import { audit, notify } from '../utils/audit.js';

const router=Router();router.use(requireAuth);

// Visits and progress notes
router.get('/visits',requirePermission('visits.read'),asyncHandler(async(req,res)=>{
 const {page,pageSize,offset}=pagination(req.query);let query=db('visits as v').join('patients as p','v.patient_id','p.id').join('users as d','v.doctor_id','d.id').select('v.*','p.first_name','p.last_name','p.file_no','d.full_name as doctor_name');if(req.user.role==='doctor')query=query.where('v.doctor_id',req.user.id);if(req.user.role==='patient'){const patient=await db('patients').where({user_id:req.user.id}).first();if(!patient)return res.json(pageResult([],0,page,pageSize));query=query.where('v.patient_id',patient.id);}if(req.query.patientId)query=query.where('v.patient_id',Number(req.query.patientId));const total=await query.clone().clearSelect().count({count:'v.id'}).first();const rows=await query.orderBy('v.created_at','desc').limit(pageSize).offset(offset);res.json(pageResult(rows.map(x=>({...x,patientName:`${x.first_name} ${x.last_name}`})),Number(total.count),page,pageSize));
}));
router.post('/visits',requirePermission('visits.write'),asyncHandler(async(req,res)=>{
 const input=z.object({patientId:z.coerce.number().int().positive(),appointmentId:z.coerce.number().int().positive().nullable().optional(),type:z.enum(['first','follow_up','consultation']).default('first'),complaint:z.string().max(4000).optional(),examination:z.string().max(8000).optional(),diagnosis:z.string().max(4000).optional()}).parse(req.body);const patient=await db('patients').where({id:input.patientId}).whereNull('deleted_at').first();if(!patient)throw new HttpError(404,'PATIENT_NOT_FOUND','المريض غير موجود.');const id=await insertAndGetId(db('visits').insert({patient_id:input.patientId,doctor_id:req.user.id,appointment_id:input.appointmentId||null,type:input.type,complaint:input.complaint||'',examination:input.examination||'',diagnosis:input.diagnosis||'',status:'draft'}));await audit(req,'visit.create','visit',id,{patientId:input.patientId});res.status(201).json({data:await db('visits').where({id}).first()});
}));
router.get('/visits/:id',requirePermission('visits.read'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('visits').where({id}).first();if(!row)throw new HttpError(404,'VISIT_NOT_FOUND','الزيارة غير موجودة.');if(req.user.role==='doctor'&&Number(row.doctor_id)!==Number(req.user.id))throw new HttpError(403,'FORBIDDEN','لا يمكنك فتح هذه الزيارة.');if(req.user.role==='patient'){const p=await db('patients').where({id:row.patient_id}).first();ensurePatientAccess(p,req.user);}const [prescriptions,labs]=await Promise.all([db('prescriptions').where({visit_id:id}),db('lab_orders').where({visit_id:id})]);await audit(req,'visit.read','visit',id);res.json({data:{...row,prescriptions,labs}});}));
router.patch('/visits/:id',requirePermission('visits.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('visits').where({id}).first();if(!row)throw new HttpError(404,'VISIT_NOT_FOUND','الزيارة غير موجودة.');if(Number(row.doctor_id)!==Number(req.user.id)&&req.user.role!=='admin')throw new HttpError(403,'FORBIDDEN','لا يمكنك تعديل هذه الزيارة.');if(row.status==='signed')throw new HttpError(409,'VISIT_SIGNED','الزيارة الموقعة لا تعدل؛ أنشئ ملاحظة متابعة.');const input=z.object({complaint:z.string().max(4000).optional(),examination:z.string().max(8000).optional(),diagnosis:z.string().max(4000).optional()}).parse(req.body);await db('visits').where({id}).update({...input,updated_at:db.fn.now()});await audit(req,'visit.update','visit',id,{fields:Object.keys(input)});res.json({data:await db('visits').where({id}).first()});}));
router.post('/visits/:id/sign',requirePermission('visits.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('visits').where({id}).first();if(!row)throw new HttpError(404,'VISIT_NOT_FOUND','الزيارة غير موجودة.');if(Number(row.doctor_id)!==Number(req.user.id)&&req.user.role!=='admin')throw new HttpError(403,'FORBIDDEN','لا يمكنك توقيع هذه الزيارة.');await db('visits').where({id}).update({status:'signed',signed_at:db.fn.now(),updated_at:db.fn.now()});await audit(req,'visit.sign','visit',id);res.json({message:'تم توقيع الزيارة.'});}));

router.get('/notes',requirePermission('visits.read'),asyncHandler(async(req,res)=>{let query=db('notes as n').join('patients as p','n.patient_id','p.id').select('n.*','p.first_name','p.last_name','p.file_no');if(req.user.role==='doctor')query=query.where('n.author_id',req.user.id);if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();query=query.where('n.patient_id',p?.id||-1);}if(req.query.patientId)query=query.where('n.patient_id',Number(req.query.patientId));const rows=await query.orderBy('n.created_at','desc').limit(100);res.json({data:rows});}));
router.post('/notes',requirePermission('visits.write'),asyncHandler(async(req,res)=>{const input=z.object({patientId:z.coerce.number().int().positive(),visitId:z.coerce.number().int().positive().nullable().optional(),title:z.string().max(180).optional(),body:z.string().trim().min(1).max(8000)}).parse(req.body);const p=await db('patients').where({id:input.patientId}).whereNull('deleted_at').first();if(!p)throw new HttpError(404,'PATIENT_NOT_FOUND','المريض غير موجود.');const id=await insertAndGetId(db('notes').insert({patient_id:input.patientId,visit_id:input.visitId||null,author_id:req.user.id,title:input.title||'ملاحظة طبية',body:input.body,has_audio:false}));await audit(req,'note.create','note',id,{patientId:input.patientId});res.status(201).json({data:await db('notes').where({id}).first()});}));

// Lab orders. Sample collection and result entry are receptionist/admin operations.
router.get('/lab-orders',requirePermission('labs.read'),asyncHandler(async(req,res)=>{let query=db('lab_orders as o').join('patients as p','o.patient_id','p.id').join('users as d','o.doctor_id','d.id').select('o.*','p.first_name','p.last_name','p.file_no','d.full_name as doctor_name');if(req.user.role==='doctor')query=query.where('o.doctor_id',req.user.id);if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();query=query.where('o.patient_id',p?.id||-1);}if(req.query.status)query=query.where('o.status',String(req.query.status));if(req.query.patientId)query=query.where('o.patient_id',Number(req.query.patientId));const rows=await query.orderBy('o.ordered_at','desc').limit(100);const ids=rows.map(x=>x.id);const items=ids.length?await db('lab_order_items as i').join('lab_tests as t','i.lab_test_id','t.id').whereIn('i.lab_order_id',ids).select('i.*','t.name_ar','t.name_en','t.unit','t.ref_min','t.ref_max','t.ref_text'):[];const byId=new Map();for(const x of items){if(!byId.has(x.lab_order_id))byId.set(x.lab_order_id,[]);byId.get(x.lab_order_id).push(x);}res.json({data:rows.map(x=>({id:x.id,patientId:x.patient_id,patientName:`${x.first_name} ${x.last_name}`,fileNo:x.file_no,doctorId:x.doctor_id,doctorName:x.doctor_name,priority:x.priority,reason:x.reason,status:x.status,orderedAt:x.ordered_at,items:byId.get(x.id)||[]}))});}));
router.post('/lab-orders',requirePermission('labs.write'),asyncHandler(async(req,res)=>{const input=z.object({patientId:z.coerce.number().int().positive(),visitId:z.coerce.number().int().positive().nullable().optional(),priority:z.enum(['normal','urgent']).default('normal'),reason:z.string().max(1000).optional(),testIds:z.array(z.coerce.number().int().positive()).min(1)}).parse(req.body);const patient=await db('patients').where({id:input.patientId}).whereNull('deleted_at').first();if(!patient)throw new HttpError(404,'PATIENT_NOT_FOUND','المريض غير موجود.');const tests=await db('lab_tests').whereIn('id',input.testIds).where({is_active:true});if(tests.length!==input.testIds.length)throw new HttpError(422,'INVALID_TEST','تحقق من أنواع التحاليل المحددة.');const id=await db.transaction(async trx=>{const orderId=await insertAndGetId(trx('lab_orders').insert({patient_id:input.patientId,doctor_id:req.user.id,visit_id:input.visitId||null,priority:input.priority,reason:input.reason||'',status:'new'}));for(const test of tests)await trx('lab_order_items').insert({lab_order_id:orderId,lab_test_id:test.id,price_snapshot:test.price});return orderId;});await audit(req,'lab.order.create','lab_order',id,{patientId:input.patientId,testIds:input.testIds});res.status(201).json({data:await db('lab_orders').where({id}).first()});}));
router.post('/lab-orders/:id/collect-sample',requirePermission('labs.collect'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('lab_orders').where({id}).first();if(!row)throw new HttpError(404,'LAB_ORDER_NOT_FOUND','طلب التحليل غير موجود.');if(row.status==='reviewed')throw new HttpError(409,'LAB_ALREADY_REVIEWED','تمت مراجعة النتائج.');await db('lab_orders').where({id}).update({status:'sample_collected',updated_at:db.fn.now()});await audit(req,'lab.sample.collect','lab_order',id);res.json({message:'تم تسجيل سحب العينة.'});}));
router.post('/lab-orders/:id/items/:itemId/result',requirePermission('labs.collect'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const itemId=idParam(req.params.itemId);const input=z.object({valueText:z.string().max(180).optional(),valueNumber:z.preprocess(value=>value===undefined?undefined:value===''||value===null?null:Number(value),z.number().finite().nullable().optional()),fileId:z.coerce.number().int().positive().optional()}).parse(req.body);const order=await db('lab_orders').where({id}).first();if(!order)throw new HttpError(404,'LAB_ORDER_NOT_FOUND','طلب التحليل غير موجود.');const item=await db('lab_order_items').where({id:itemId,lab_order_id:id}).first();if(!item)throw new HttpError(404,'LAB_ITEM_NOT_FOUND','التحليل غير موجود في هذا الطلب.');const test=await db('lab_tests').where({id:item.lab_test_id}).first();if(input.fileId){const file=await db('files').where({id:input.fileId}).first();if(!file||Number(file.patient_id)!==Number(order.patient_id))throw new HttpError(422,'FILE_MISMATCH','ملف النتيجة غير مرتبط بهذا المريض.');}const n=input.valueNumber;const flag=n==null?'unknown':((test.ref_min!=null&&n<Number(test.ref_min))||(test.ref_max!=null&&n>Number(test.ref_max))?'out_of_range':'normal');await db.transaction(async trx=>{await trx('lab_order_items').where({id:itemId}).update({value_text:input.valueText||String(n??''),value_number:n??null,flag,file_id:input.fileId||null,resulted_by:req.user.id,resulted_at:trx.fn.now()});const remaining=await trx('lab_order_items').where({lab_order_id:id}).whereNull('resulted_at').count({count:'*'}).first();if(Number(remaining.count)===0)await trx('lab_orders').where({id}).update({status:'result_ready',updated_at:trx.fn.now()});});await audit(req,'lab.result.create','lab_order_item',itemId,{flag});if(flag==='out_of_range'){await notify(order.doctor_id,'lab_alert','نتيجة تحليل خارج المعدل الطبيعي',`${test.name_ar}: ${n} ${test.unit||''}.`,'/doctor/labs');}res.json({message:'تم حفظ نتيجة التحليل.',flag});}));
router.post('/lab-orders/:id/review',requirePermission('labs.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('lab_orders').where({id}).first();if(!row)throw new HttpError(404,'LAB_ORDER_NOT_FOUND','طلب التحليل غير موجود.');if(req.user.role==='doctor'&&Number(row.doctor_id)!==Number(req.user.id))throw new HttpError(403,'FORBIDDEN','لا يمكنك مراجعة طلب طبيب آخر.');await db('lab_orders').where({id}).update({status:'reviewed',updated_at:db.fn.now()});await audit(req,'lab.review','lab_order',id);res.json({message:'تم تأكيد مراجعة النتائج.'});}));

// Prescriptions: only doctor/admin can write; reception and the owning patient can read.
router.get('/prescriptions',requirePermission('prescriptions.read'),asyncHandler(async(req,res)=>{let query=db('prescriptions as r').join('patients as p','r.patient_id','p.id').join('users as d','r.doctor_id','d.id').select('r.*','p.first_name','p.last_name','p.file_no','d.full_name as doctor_name');if(req.user.role==='doctor')query=query.where('r.doctor_id',req.user.id);if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();query=query.where('r.patient_id',p?.id||-1);}if(req.query.patientId)query=query.where('r.patient_id',Number(req.query.patientId));const rows=await query.orderBy('r.issued_at','desc').limit(100);const ids=rows.map(x=>x.id);const items=ids.length?await db('prescription_items').whereIn('prescription_id',ids):[];const byId=new Map();for(const x of items){if(!byId.has(x.prescription_id))byId.set(x.prescription_id,[]);byId.get(x.prescription_id).push(x);}res.json({data:rows.map(x=>({id:x.id,patientId:x.patient_id,patientName:`${x.first_name} ${x.last_name}`,fileNo:x.file_no,doctorId:x.doctor_id,doctorName:x.doctor_name,diagnosis:x.diagnosis,recommendations:x.recommendations,status:x.status,issuedAt:x.issued_at,items:byId.get(x.id)||[]}))});}));
router.post('/prescriptions',requirePermission('prescriptions.write'),asyncHandler(async(req,res)=>{const input=z.object({patientId:z.coerce.number().int().positive(),visitId:z.coerce.number().int().positive().nullable().optional(),diagnosis:z.string().max(3000).optional(),recommendations:z.string().max(5000).optional(),items:z.array(z.object({medicationId:z.coerce.number().int().positive().nullable().optional(),name:z.string().trim().min(2).max(180),dose:z.string().max(120).optional(),frequency:z.string().max(160).optional(),route:z.string().max(64).optional(),duration:z.string().max(100).optional(),instructions:z.string().max(1000).optional()})).min(1)}).parse(req.body);const patient=await db('patients').where({id:input.patientId}).whereNull('deleted_at').first();if(!patient)throw new HttpError(404,'PATIENT_NOT_FOUND','المريض غير موجود.');const medical=await db('patient_medical').where({patient_id:patient.id}).first();const allergyText=(medical?.allergies||'').toLowerCase();const warnings=input.items.filter(x=>allergyText&&allergyText.includes(x.name.toLowerCase())).map(x=>x.name);const id=await db.transaction(async trx=>{const prescriptionId=await insertAndGetId(trx('prescriptions').insert({patient_id:input.patientId,doctor_id:req.user.id,visit_id:input.visitId||null,diagnosis:input.diagnosis||'',recommendations:input.recommendations||'',status:'draft'}));for(const item of input.items)await trx('prescription_items').insert({prescription_id:prescriptionId,medication_id:item.medicationId||null,name_snapshot:item.name,dose:item.dose||'',frequency:item.frequency||'',route:item.route||'',duration:item.duration||'',instructions:item.instructions||''});return prescriptionId;});await audit(req,'prescription.create','prescription',id,{patientId:input.patientId,allergyWarnings:warnings});res.status(201).json({data:await db('prescriptions').where({id}).first(),allergyWarnings:warnings});}));
router.get('/prescriptions/:id',requirePermission('prescriptions.read'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const prescription=await db('prescriptions').where({id}).first();if(!prescription)throw new HttpError(404,'PRESCRIPTION_NOT_FOUND','الروشتة غير موجودة.');if(req.user.role==='doctor'&&Number(prescription.doctor_id)!==Number(req.user.id))throw new HttpError(403,'FORBIDDEN','لا يمكنك فتح هذه الروشتة.');if(req.user.role==='patient'){const patient=await db('patients').where({id:prescription.patient_id}).first();ensurePatientAccess(patient,req.user);}const items=await db('prescription_items').where({prescription_id:id});await audit(req,'prescription.read','prescription',id);res.json({data:{...prescription,items}});}));
router.patch('/prescriptions/:id',requirePermission('prescriptions.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('prescriptions').where({id}).first();if(!row)throw new HttpError(404,'PRESCRIPTION_NOT_FOUND','الروشتة غير موجودة.');if(row.status!=='draft')throw new HttpError(409,'PRESCRIPTION_IMMUTABLE','الروشتة الموقعة غير قابلة للتعديل. أنشئ نسخة معدّلة.');const input=z.object({diagnosis:z.string().max(3000).optional(),recommendations:z.string().max(5000).optional()}).parse(req.body);await db('prescriptions').where({id}).update({...input,updated_at:db.fn.now()});await audit(req,'prescription.update','prescription',id,{fields:Object.keys(input)});res.json({data:await db('prescriptions').where({id}).first()});}));
router.post('/prescriptions/:id/sign',requirePermission('prescriptions.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('prescriptions').where({id}).first();if(!row)throw new HttpError(404,'PRESCRIPTION_NOT_FOUND','الروشتة غير موجودة.');if(row.status!=='draft')throw new HttpError(409,'PRESCRIPTION_IMMUTABLE','هذه الروشتة موقعة بالفعل.');await db('prescriptions').where({id}).update({status:'active',issued_at:db.fn.now(),updated_at:db.fn.now()});await audit(req,'prescription.sign','prescription',id);res.json({message:'تم توقيع الروشتة.'});}));

router.get('/lab-trend/:patientId',requirePermission('labs.read'),asyncHandler(async(req,res)=>{const patientId=idParam(req.params.patientId);const patient=await db('patients').where({id:patientId}).first();if(!patient)throw new HttpError(404,'PATIENT_NOT_FOUND','المريض غير موجود.');if(req.user.role==='patient')ensurePatientAccess(patient,req.user);const testId=req.query.testId?Number(req.query.testId):null;let q=db('lab_order_items as i').join('lab_orders as o','i.lab_order_id','o.id').join('lab_tests as t','i.lab_test_id','t.id').where('o.patient_id',patientId).whereNotNull('i.value_number').select('i.value_number','i.flag','i.resulted_at','t.name_ar','t.unit','t.ref_min','t.ref_max');if(testId)q=q.where('i.lab_test_id',testId);const rows=await q.orderBy('i.resulted_at','asc').limit(100);res.json({data:rows});}));

export default router;
