import { Router } from 'express';
import dayjs from 'dayjs';
import { localDayRange } from '../utils/time.js';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createReadStream } from 'node:fs';
import { promisify } from 'node:util';
import { execFile } from 'node:child_process';
import { z } from 'zod';
import { db, clientName } from '../db/knex.js';
import { insertAndGetId } from '../db/insert-id.js';
import { env } from '../config/env.js';
import { requireAuth, requirePermission, requireRole } from '../middleware/auth.js';
import { asyncHandler, HttpError, idParam } from '../utils/http.js';
import { audit, notify } from '../utils/audit.js';

const router=Router();router.use(requireAuth);const execFileAsync=promisify(execFile);

router.get('/notifications',asyncHandler(async(req,res)=>{const rows=await db('notifications').where({user_id:req.user.id}).orderBy('created_at','desc').limit(100);res.json({data:rows.map(x=>({...x,read:Boolean(x.read_at)})),unread:rows.filter(x=>!x.read_at).length});}));
router.post('/notifications/read-all',asyncHandler(async(req,res)=>{await db('notifications').where({user_id:req.user.id}).whereNull('read_at').update({read_at:db.fn.now(),updated_at:db.fn.now()});res.json({message:'تم تحديد الإشعارات كمقروءة.'});}));
router.post('/notifications/:id/read',asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const row=await db('notifications').where({id,user_id:req.user.id}).first();if(!row)throw new HttpError(404,'NOTIFICATION_NOT_FOUND','الإشعار غير موجود.');await db('notifications').where({id}).update({read_at:db.fn.now(),updated_at:db.fn.now()});res.json({message:'تم تحديد الإشعار كمقروء.'});}));

const allowedGroups=['general','booking','billing','notifications','security','backup'];
router.get('/settings/:group',requireRole('admin'),asyncHandler(async(req,res)=>{const group=String(req.params.group);if(!allowedGroups.includes(group))throw new HttpError(404,'SETTINGS_GROUP_NOT_FOUND','مجموعة الإعدادات غير موجودة.');const row=await db('settings').where({key:`settings:${group}`}).first();res.json({data:row?JSON.parse(row.value):{}});}));
router.put('/settings/:group',requireRole('admin'),asyncHandler(async(req,res)=>{const group=String(req.params.group);if(!allowedGroups.includes(group))throw new HttpError(404,'SETTINGS_GROUP_NOT_FOUND','مجموعة الإعدادات غير موجودة.');if(!req.body||typeof req.body!=='object'||Array.isArray(req.body))throw new HttpError(422,'INVALID_SETTINGS','بيانات الإعدادات غير صالحة.');const clean={...req.body};delete clean.API_KEY;delete clean.apiKey;const key=`settings:${group}`;const existing=await db('settings').where({key}).first();if(existing)await db('settings').where({key}).update({value:JSON.stringify(clean),updated_at:db.fn.now()});else await db('settings').insert({key,value:JSON.stringify(clean)});await audit(req,'settings.update','settings',group,{keys:Object.keys(clean)});res.json({data:clean,message:'تم حفظ الإعدادات.'});}));
router.get('/settings/permissions',requireRole('admin'),asyncHandler(async(req,res)=>{const rows=await db('role_permissions').orderBy(['role','permission_key']);const grouped={};for(const x of rows){grouped[x.role]??={};grouped[x.role][x.permission_key]=Boolean(x.allowed);}res.json({data:grouped});}));
router.put('/settings/permissions',requireRole('admin'),asyncHandler(async(req,res)=>{const input=z.record(z.record(z.boolean())).parse(req.body);await db.transaction(async trx=>{for(const [role,permissions] of Object.entries(input)){if(!['doctor','receptionist','patient'].includes(role))continue;for(const [permission_key,allowed] of Object.entries(permissions)){const row=await trx('role_permissions').where({role,permission_key}).first();if(row)await trx('role_permissions').where({id:row.id}).update({allowed,updated_at:trx.fn.now()});else await trx('role_permissions').insert({role,permission_key,allowed});}}});await audit(req,'settings.permissions.update','settings','permissions');res.json({message:'تم تحديث مصفوفة الصلاحيات.'});}));

router.get('/reports/overview',requireRole('admin','doctor','receptionist'),asyncHandler(async(req,res)=>{
 const today=dayjs().format('YYYY-MM-DD');const [dayStart,dayEnd]=localDayRange();let appointmentQuery=db('appointments').whereNot('status','cancelled');appointmentQuery=clientName==='mysql2'?appointmentQuery.whereRaw('DATE(??) = ?', ['start_at',today]):appointmentQuery.where('start_at','>=',dayStart).where('start_at','<',dayEnd);let queueQuery=db('queue_entries').where({queue_date:today,status:'waiting'});let labQuery=db('lab_orders').whereIn('status',['new','sample_collected','result_ready']);let visitQuery=db('visits').select('diagnosis','created_at');
 if(req.user.role==='doctor'){appointmentQuery=appointmentQuery.where({doctor_id:req.user.id});queueQuery=queueQuery.where({doctor_id:req.user.id});labQuery=labQuery.where({doctor_id:req.user.id});visitQuery=visitQuery.where({doctor_id:req.user.id});}
 let paymentQuery=db('payments');paymentQuery=clientName==='mysql2'?paymentQuery.whereRaw('DATE(??) = ?', ['paid_at',today]):paymentQuery.where('paid_at','>=',dayStart).where('paid_at','<',dayEnd);paymentQuery=paymentQuery.select('amount');
 const [patientCount,todayAppt,waiting,labPending,invoices,paymentRows,visits]=await Promise.all([
 db('patients').whereNull('deleted_at').count({count:'*'}).first(),appointmentQuery.count({count:'*'}).first(),queueQuery.count({count:'*'}).first(),labQuery.count({count:'*'}).first(),req.user.role==='doctor'?Promise.resolve([]):db('invoices').whereIn('status',['unpaid','partial']).select('total','paid_amount'),req.user.role==='doctor'?Promise.resolve([]):paymentQuery,req.user.role==='receptionist'?Promise.resolve([]):visitQuery]);
 const outstanding=invoices.reduce((a,x)=>a+Number(x.total)-Number(x.paid_amount),0);const revenue=paymentRows.reduce((a,x)=>a+Number(x.amount),0);const diagnoses={};for(const v of visits){const k=String(v.diagnosis||'').trim();if(k)diagnoses[k]=(diagnoses[k]||0)+1;}
 res.json({data:{activePatients:Number(patientCount.count),appointmentsToday:Number(todayAppt.count),waitingNow:Number(waiting.count),labsAwaitingReview:Number(labPending.count),outstanding:Math.round(outstanding*100)/100,revenueToday:Math.round(revenue*100)/100,diagnoses:Object.entries(diagnoses).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,value])=>({name,value}))}});
}));
router.get('/reports/lab-trend',requireRole('admin','doctor','receptionist'),asyncHandler(async(req,res)=>{const since=dayjs().subtract(56,'day').toISOString();let query=db('lab_orders').where('ordered_at','>=',since).select('ordered_at');if(req.user.role==='doctor')query=query.where({doctor_id:req.user.id});const rows=await query;const buckets=Array.from({length:8},(_,i)=>({week:`الأسبوع ${i+1}`,count:0}));for(const row of rows){const diff=dayjs().diff(dayjs(row.ordered_at),'day');const index=Math.max(0,7-Math.floor(diff/7));if(index<8)buckets[index].count++;}res.json({data:buckets});}));
router.get('/reports/diagnoses',requirePermission('reports.clinical'),asyncHandler(async(req,res)=>{const rows=await db('visits').select('diagnosis');const counts={};for(const x of rows){const key=String(x.diagnosis||'غير مصنف').trim()||'غير مصنف';counts[key]=(counts[key]||0)+1;}res.json({data:Object.entries(counts).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,10)});}));
router.get('/reports/export',requirePermission('reports.clinical'),asyncHandler(async(req,res)=>{const type=String(req.query.type||'patients');const map={patients:['patients',['file_no','first_name','last_name','sex','phone','email','status']],appointments:['appointments',['patient_id','doctor_id','service_id','type','start_at','end_at','status']],invoices:['invoices',['number','patient_id','subtotal','tax_amount','total','paid_amount','status','issued_at']],audit:['audit_logs',['user_id','action','entity','entity_id','ip','created_at']]};const selected=map[type];if(!selected)throw new HttpError(422,'EXPORT_TYPE_INVALID','نوع التصدير غير مدعوم.');const rows=await db(selected[0]).select(selected[1]).limit(10000);const escape=(v)=>`"${String(v??'').replaceAll('"','""')}"`;const csv=[selected[1].join(','),...rows.map(row=>selected[1].map(col=>escape(row[col])).join(','))].join('\r\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="clinico-${type}-${dayjs().format('YYYYMMDD')}.csv"`);res.send('\uFEFF'+csv);await audit(req,'report.export','report',type,{rows:rows.length});}));

router.get('/search',asyncHandler(async(req,res)=>{const q=String(req.query.q||'').trim();if(q.length<2)return res.json({data:{patients:[],labs:[],prescriptions:[],invoices:[]}});const like=`%${q}%`;const result={patients:[],labs:[],prescriptions:[],invoices:[]};if(['admin','doctor','receptionist'].includes(req.user.role)){
 result.patients=await db('patients').whereNull('deleted_at').andWhere(b=>b.where('first_name','like',like).orWhere('last_name','like',like).orWhere('phone','like',like).orWhere('file_no','like',like)).limit(5).select('id','file_no','first_name','last_name','phone');
 result.labs=await db('lab_orders as o').join('patients as p','o.patient_id','p.id').join('lab_order_items as i','i.lab_order_id','o.id').join('lab_tests as t','i.lab_test_id','t.id').where(b=>b.where('p.first_name','like',like).orWhere('p.last_name','like',like).orWhere('t.name_ar','like',like)).limit(5).select('o.id','o.status','p.first_name','p.last_name','t.name_ar');
 result.prescriptions=await db('prescriptions as r').join('patients as p','r.patient_id','p.id').where(b=>b.where('p.first_name','like',like).orWhere('p.last_name','like',like).orWhere('r.diagnosis','like',like)).limit(5).select('r.id','r.status','p.first_name','p.last_name');
 if(['admin','receptionist'].includes(req.user.role))result.invoices=await db('invoices as i').join('patients as p','i.patient_id','p.id').where(b=>b.where('i.number','like',like).orWhere('p.first_name','like',like).orWhere('p.last_name','like',like)).limit(5).select('i.id','i.number','i.total','i.status','p.first_name','p.last_name');
 }else if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();if(p){result.patients=[{id:p.id,file_no:p.file_no,first_name:p.first_name,last_name:p.last_name,phone:p.phone}];result.labs=await db('lab_orders as o').join('lab_order_items as i','i.lab_order_id','o.id').join('lab_tests as t','i.lab_test_id','t.id').where('o.patient_id',p.id).where('t.name_ar','like',like).limit(5).select('o.id','o.status','t.name_ar');result.prescriptions=await db('prescriptions').where({patient_id:p.id}).where('diagnosis','like',like).limit(5);}}
 res.json({data:result});
}));

router.get('/audit',requireRole('admin'),asyncHandler(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1);const pageSize=Math.min(100,Number(req.query.pageSize)||50);const rows=await db('audit_logs as a').leftJoin('users as u','a.user_id','u.id').select('a.*','u.full_name','u.role').orderBy('a.created_at','desc').limit(pageSize).offset((page-1)*pageSize);const total=await db('audit_logs').count({count:'*'}).first();res.json({data:rows,pagination:{page,pageSize,total:Number(total.count)}});}));

router.get('/threads',requirePermission('messages.read'),asyncHandler(async(req,res)=>{let query=db('message_threads as t').join('patients as p','t.patient_id','p.id').select('t.*','p.first_name','p.last_name','p.file_no');if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();query=query.where('t.patient_id',p?.id||-1);}const rows=await query.orderBy('t.updated_at','desc').limit(100);res.json({data:rows.map(x=>({...x,patientName:`${x.first_name} ${x.last_name}`}))});}));
router.post('/threads',requirePermission('messages.write'),asyncHandler(async(req,res)=>{const input=z.object({patientId:z.coerce.number().int().positive().optional(),subject:z.string().max(180).optional(),body:z.string().trim().min(1).max(5000)}).parse(req.body);let patientId=input.patientId;if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();patientId=p?.id;}if(!patientId)throw new HttpError(422,'PATIENT_REQUIRED','اختر المريض.');const id=await db.transaction(async trx=>{const threadId=await insertAndGetId(trx('message_threads').insert({patient_id:patientId,subject:input.subject||'استفسار جديد',status:'open'}));await trx('messages').insert({thread_id:threadId,sender_id:req.user.id,body:input.body});return threadId;});await audit(req,'message.thread.create','thread',id);res.status(201).json({data:await db('message_threads').where({id}).first()});}));
router.get('/threads/:id/messages',requirePermission('messages.read'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const thread=await db('message_threads').where({id}).first();if(!thread)throw new HttpError(404,'THREAD_NOT_FOUND','المحادثة غير موجودة.');if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();if(Number(p?.id)!==Number(thread.patient_id))throw new HttpError(404,'THREAD_NOT_FOUND','المحادثة غير موجودة.');}const rows=await db('messages as m').join('users as u','m.sender_id','u.id').where('m.thread_id',id).select('m.*','u.full_name as sender_name','u.role as sender_role').orderBy('m.created_at');await db('messages').where({thread_id:id}).whereNot('sender_id',req.user.id).whereNull('read_at').update({read_at:db.fn.now(),updated_at:db.fn.now()});res.json({data:rows});}));
router.post('/threads/:id/messages',requirePermission('messages.write'),asyncHandler(async(req,res)=>{const id=idParam(req.params.id);const thread=await db('message_threads').where({id}).first();if(!thread)throw new HttpError(404,'THREAD_NOT_FOUND','المحادثة غير موجودة.');if(req.user.role==='patient'){const p=await db('patients').where({user_id:req.user.id}).first();if(Number(p?.id)!==Number(thread.patient_id))throw new HttpError(404,'THREAD_NOT_FOUND','المحادثة غير موجودة.');}const input=z.object({body:z.string().trim().min(1).max(5000)}).parse(req.body);const msgId=await insertAndGetId(db('messages').insert({thread_id:id,sender_id:req.user.id,body:input.body}));await db('message_threads').where({id}).update({updated_at:db.fn.now()});await audit(req,'message.create','message',msgId,{threadId:id});res.status(201).json({data:await db('messages').where({id:msgId}).first()});}));

router.get('/doctors/:id/working-hours',requireRole('admin','doctor'),asyncHandler(async(req,res)=>{const doctorId=idParam(req.params.id);if(req.user.role==='doctor'&&doctorId!==Number(req.user.id))throw new HttpError(403,'FORBIDDEN','يمكن للطبيب إدارة جدوله فقط.');const data=await db('working_hours').where({doctor_id:doctorId}).orderBy('weekday');res.json({data});}));
router.put('/doctors/:id/working-hours',requireRole('admin','doctor'),asyncHandler(async(req,res)=>{const doctorId=idParam(req.params.id);if(req.user.role==='doctor'&&doctorId!==Number(req.user.id))throw new HttpError(403,'FORBIDDEN','يمكن للطبيب إدارة جدوله فقط.');const input=z.object({hours:z.array(z.object({weekday:z.coerce.number().int().min(0).max(6),isOpen:z.boolean(),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/)})).length(7),avgVisitMinutes:z.coerce.number().int().min(5).max(120).optional()}).parse(req.body);await db.transaction(async trx=>{for(const h of input.hours){if(h.endTime<=h.startTime)throw new HttpError(422,'INVALID_HOURS','وقت نهاية الدوام يجب أن يأتي بعد البداية.');const existing=await trx('working_hours').where({doctor_id:doctorId,weekday:h.weekday}).first();const values={is_open:h.isOpen,start_time:h.startTime,end_time:h.endTime};if(existing)await trx('working_hours').where({id:existing.id}).update(values);else await trx('working_hours').insert({doctor_id:doctorId,weekday:h.weekday,...values});}if(input.avgVisitMinutes)await trx('doctor_profiles').where({user_id:doctorId}).update({avg_visit_minutes:input.avgVisitMinutes,updated_at:trx.fn.now()});});await audit(req,'doctor.working_hours.update','doctor',doctorId);res.json({message:'تم حفظ ساعات العمل.'});}));

router.get('/backups',requireRole('admin'),asyncHandler(async(req,res)=>{
 if(env.isVercel)return res.json({data:[],storageDisabled:true});
 const rows=await db('backups').orderBy('created_at','desc').limit(50);res.json({data:rows});
}));
router.post('/backups',requireRole('admin'),asyncHandler(async(req,res)=>{
 if(env.isVercel)throw new HttpError(503,'BACKUP_STORAGE_DISABLED','النسخ إلى قرص Vercel غير دائم. استخدم نسخ Neon أو مخزنًا دائمًا.');
 await fs.mkdir(env.backupDir,{recursive:true});
 const extension=clientName==='better-sqlite3'?'sqlite':'sql';
 const filename=`clinico-${dayjs().format('YYYYMMDD-HHmmss')}.${extension}`;const target=path.join(env.backupDir,filename);
 if(clientName==='better-sqlite3'){
  await db.raw('PRAGMA wal_checkpoint(FULL)');await fs.copyFile(env.dbFilename,target);
 }else if(clientName==='pg'){
  const connection=new URL(env.databaseUrl);const database=decodeURIComponent(connection.pathname.replace(/^\//,''));
  const {stdout}=await execFileAsync('pg_dump',['--host',connection.hostname,'--port',connection.port||'5432','--username',decodeURIComponent(connection.username),'--dbname',database,'--no-owner','--no-privileges'],{maxBuffer:100*1024*1024,env:{...process.env,PGPASSWORD:decodeURIComponent(connection.password),PGSSLMODE:'require'}});
  await fs.writeFile(target,stdout);
 }else{
  const {stdout}=await execFileAsync('mysqldump',['--host',env.dbHost,'--port',String(env.dbPort),'--user',env.dbUser,env.dbName],{maxBuffer:100*1024*1024,env:{...process.env,MYSQL_PWD:env.dbPassword}});
  await fs.writeFile(target,stdout);
 }
 const stat=await fs.stat(target);const id=await insertAndGetId(db('backups').insert({path:target,size:stat.size,status:'complete',created_by:req.user.id}));
 await audit(req,'backup.create','backup',id,{size:stat.size});res.status(201).json({data:await db('backups').where({id}).first(),message:'تم إنشاء نسخة احتياطية.'});
}));
router.get('/backups/:id/download',requireRole('admin'),asyncHandler(async(req,res)=>{
 if(env.isVercel)throw new HttpError(503,'BACKUP_STORAGE_DISABLED','تنزيل النسخ من قرص Vercel غير متاح؛ استخدم مخزنًا دائمًا.');
 const id=idParam(req.params.id);const backup=await db('backups').where({id,status:'complete'}).first();if(!backup)throw new HttpError(404,'BACKUP_NOT_FOUND','النسخة الاحتياطية غير موجودة.');await audit(req,'backup.download','backup',id);res.download(backup.path,path.basename(backup.path));
}));

export default router;
