import React,{useEffect,useMemo,useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,PieChart,Pie,Cell} from 'recharts';
import {Users,CalendarCheck2,Clock3,Wallet,FlaskConical,FileHeart,UserPlus,CalendarPlus,ArrowLeft,ArrowUpLeft,ArrowUpRight,HeartPulse,Activity,FileText,ClipboardCheck,Search,CheckCircle2,AlertTriangle,ChevronLeft,ArrowRight,ArrowUp,TrendingUp,Plus,Stethoscope,CalendarClock,ReceiptText} from 'lucide-react';
import {Link,useNavigate} from 'react-router-dom';
import {api} from '../services/api.js';
import {useAuth} from '../app/AuthContext.jsx';
import {Card,PageHeading,StatCard,StatusBadge,Badge,Button,EmptyState,useToast} from '../components/UI.jsx';

const currency=(n)=>`${Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0})} ج.م`;
export default function Dashboard({role}){const {user}=useAuth();const [overview,setOverview]=useState(null);const [billing,setBilling]=useState(null);const [appointments,setAppointments]=useState([]);const [patients,setPatients]=useState([]);const [queue,setQueue]=useState([]);const [trend,setTrend]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const toast=useToast();
 useEffect(()=>{let active=true;setLoading(true);const promises=[api('/reports/overview').catch(()=>null),api('/billing/summary').catch(()=>null),api('/appointments?pageSize=8').catch(()=>null),api('/patients?pageSize=5').catch(()=>null),api('/queue').catch(()=>null),api('/reports/lab-trend').catch(()=>null)];Promise.all(promises).then(([o,b,a,p,q,t])=>{if(!active)return;setOverview(o?.data||null);setBilling(b?.data||null);setAppointments(a?.data||[]);setPatients(p?.data||[]);setQueue(q?.data||[]);setTrend(t?.data||[]);setLoading(false);}).catch(e=>{if(active){setError(e.message);setLoading(false);}});const interval=setInterval(()=>api('/queue').then(r=>active&&setQueue(r.data||[])).catch(()=>{}),15000);return()=>{active=false;clearInterval(interval);};},[]);
 const isDoctor=role==='doctor',isReception=role==='receptionist';const prefix=isDoctor?'/doctor':isReception?'/reception':'/admin';
 const stats=isDoctor?[{label:'زيارات اليوم',value:overview?.appointmentsToday??'—',icon:CalendarCheck2,tone:'teal',caption:'مواعيد مسجلة اليوم'},{label:'في قائمة الانتظار',value:overview?.waitingNow??'—',icon:Clock3,tone:'aqua',caption:'يتم التحديث تلقائيًا'},{label:'تحاليل بانتظار المراجعة',value:overview?.labsAwaitingReview??'—',icon:FlaskConical,tone:'gold',caption:'نتائج تحتاج مراجعة'},{label:'مرضاي',value:overview?.activePatients??'—',icon:Users,tone:'violet',caption:'ملفات نشطة'}]:isReception?[{label:'مواعيد اليوم',value:overview?.appointmentsToday??'—',icon:CalendarCheck2,tone:'teal',caption:'مواعيد مؤكدة'},{label:'رقم الانتظار الحالي',value:queue.find(x=>x.status==='called')?.number??'—',icon:Clock3,tone:'aqua',caption:'الدور الجاري'},{label:'إيراد اليوم',value:currency(billing?.revenueToday),icon:Wallet,tone:'green',caption:'من الدفعات المسجلة'},{label:'فواتير معلقة',value:billing?.overdueCount??'—',icon:ReceiptText,tone:'gold',caption:'تحتاج إلى متابعة'}]:[{label:'المرضى النشطون',value:overview?.activePatients?.toLocaleString('en-US')??'—',icon:Users,tone:'teal',caption:'ملفات مرضى محفوظة'},{label:'مواعيد اليوم',value:overview?.appointmentsToday??'—',icon:CalendarCheck2,tone:'aqua',caption:'لدى الفريق الطبي'},{label:'في الانتظار',value:overview?.waitingNow??'—',icon:Clock3,tone:'gold',caption:'يتم التحديث تلقائيًا'},{label:'الرصيد المستحق',value:currency(overview?.outstanding),icon:Wallet,tone:'violet',caption:'إجمالي الفواتير غير المسددة'}];
 return <div className="dashboard-page"><PageHeading eyebrow={isDoctor?'مساحة الطبيب':isReception?'إدارة الاستقبال':'إدارة العيادة'} title={`مرحبًا، ${user?.fullName?.split(' ')[0]}`} description={`إليك ملخص العيادة اليوم · ${new Intl.DateTimeFormat('ar-EG-u-nu-latn',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date())}`} actions={<><Link className="btn btn-outline" to={`${prefix}/patients/new`}><UserPlus size={16}/> مريض جديد</Link><Link className="btn btn-primary" to={`${prefix}/appointments/new`}><CalendarPlus size={16}/> حجز موعد</Link></>}/>
 {error&&<div className="form-alert error">تعذر تحميل بعض البيانات: {error}</div>}
 <div className="stats-grid">{stats.map(x=><StatCard key={x.label} {...x}/>)}</div>
 <div className="dashboard-grid">
  <Card className="dashboard-schedule"><div className="card-heading"><div><h2>{isDoctor?'جدول اليوم':isReception?'قائمة عمل اليوم':'نظرة عامة على المواعيد'}</h2><p>مواعيد الزيارة وحالة الحضور</p></div><Link to={`${prefix}/appointments`} className="text-link">عرض الجدول <ArrowLeft size={15}/></Link></div>{loading?<div className="skeleton-table"><i/><i/><i/><i/></div>:appointments.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>الوقت</th><th>المريض</th><th>نوع الزيارة</th><th>الطبيب</th><th>الحالة</th></tr></thead><tbody>{appointments.slice(0,6).map(a=><tr key={a.id}><td className="time-cell">{formatTime(a.startAt)}</td><td><strong>{a.patientName}</strong><small className="sub-cell">{a.fileNo}</small></td><td><VisitType type={a.type}/></td><td>{a.doctorName||'—'}</td><td><StatusBadge status={a.status}/></td></tr>)}</tbody></table></div>:<EmptyState icon={CalendarCheck2} title="لا توجد مواعيد بعد اليوم" description="أضف موعدًا للبدء في تنظيم يوم العيادة." action={<Link className="btn btn-outline btn-sm" to={`${prefix}/appointments/new`}>حجز موعد</Link>}/>}</Card>
  <Card className="new-patients"><div className="card-heading"><div><h2>آخر المرضى المسجلين</h2><p>أحدث الملفات الطبية</p></div><span className="round-icon"><Users size={18}/></span></div>{patients.length?<div className="patient-mini-list">{patients.slice(0,5).map(p=><Link to={`${prefix}/patients/${p.id}`} key={p.id} className="patient-mini"><span className="avatar-mini">{p.firstName?.[0]}</span><span className="mini-name"><b>{p.fullName}</b><small>{p.fileNo} · {p.phone||'بدون هاتف'}</small></span><ChevronLeft size={16}/></Link>)}</div>:<EmptyState title="لا توجد ملفات" description="ستظهر الملفات الجديدة هنا."/>}<Link className="subtle-link" to={`${prefix}/patients`}>فتح قائمة المرضى <ArrowLeft size={15}/></Link></Card>
  <Card className="queue-card"><div className="card-heading"><div><h2>الطابور الحالي</h2><p>تحديث مباشر كل 15 ثانية</p></div><Badge tone="info"><span className="live-dot"/> مباشر</Badge></div>{queue.length?<><div className="queue-current">{(()=>{const curr=queue.find(x=>x.status==='called'||x.status==='in_visit');return <><small>الدور الحالي</small><strong>{curr?.number??'—'}</strong><b>{curr?.patientName||'لا يوجد مريض في الكشف'}</b></>})()}</div><div className="queue-summary"><span><Clock3 size={15}/> {queue.filter(x=>x.status==='waiting').length} مرضى ينتظرون</span><Link to={`${prefix}/queue`}>إدارة الطابور <ArrowLeft size={14}/></Link></div></>:<div className="queue-empty"><Clock3 size={24}/><span>لا يوجد مريض في الطابور</span></div>}</Card>
  <Card className="trend-card"><div className="card-heading"><div><h2>طلبات التحاليل</h2><p>اتجاه الطلبات خلال آخر 8 أسابيع</p></div><span className="round-icon"><Activity size={18}/></span></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:8,right:6,left:-26,bottom:0}}><defs><linearGradient id="tealArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#24b5ad" stopOpacity={0.25}/><stop offset="1" stopColor="#24b5ad" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" stroke="var(--border)" vertical={false}/><XAxis dataKey="week" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><Tooltip contentStyle={{direction:'rtl',borderRadius:12,border:'1px solid var(--border)',fontFamily:'inherit'}}/><Area type="monotone" dataKey="count" stroke="#0b7778" strokeWidth={3} fill="url(#tealArea)"/></AreaChart></ResponsiveContainer></div></Card>
 </div>
 <div className="dashboard-bottom-grid"><Card className="quick-actions"><div className="card-heading"><div><h2>إجراءات سريعة</h2><p>وصول مباشر إلى المهام المتكررة</p></div></div><div className="quick-action-grid"><QuickAction icon={UserPlus} title="إضافة مريض" to={`${prefix}/patients/new`}/><QuickAction icon={CalendarPlus} title="حجز موعد" to={`${prefix}/appointments/new`}/><QuickAction icon={ClipboardCheck} title="إدارة الطابور" to={`${prefix}/queue`}/><QuickAction icon={FlaskConical} title="التحاليل" to={`${prefix}/labs`}/></div></Card><Card className="insights-card"><div className="card-heading"><div><h2>حالة العيادة</h2><p>مؤشرات تشغيلية مختصرة</p></div></div><div className="insight-row"><span className="insight-icon green"><CheckCircle2 size={17}/></span><span><b>قاعدة البيانات</b><small>متصلة وتحفظ التغييرات</small></span><Badge tone="success">نشطة</Badge></div><div className="insight-row"><span className="insight-icon aqua"><ShieldCheckIcon/></span><span><b>صلاحيات الحسابات</b><small>حسب دور المستخدم</small></span><Badge tone="info">مفعّلة</Badge></div><div className="insight-row"><span className="insight-icon gold"><AlertTriangle size={17}/></span><span><b>تحاليل بانتظار المراجعة</b><small>تابع النتائج الجديدة</small></span><b className="insight-number">{overview?.labsAwaitingReview??0}</b></div></Card></div>
 </div>;
}
function ShieldCheckIcon(){return <FileHeart size={17}/>}
function VisitType({type}){const map={first:['كشف أول','teal'],follow_up:['متابعة','info'],consultation:['استشارة','aqua'],lab:['تحليل','gold']};const [label,tone]=map[type]||['زيارة','neutral'];return <Badge tone={tone}>{label}</Badge>}
function QuickAction({icon:Icon,title,to}){return <Link to={to} className="quick-action"><span><Icon size={19}/></span><b>{title}</b><ArrowLeft size={14}/></Link>}
function formatTime(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('ar-EG-u-nu-latn',{hour:'2-digit',minute:'2-digit'}).format(date);}
function trendData(seed){return Array.from({length:8},(_,i)=>({name:`أ${i+1}`,count:Math.max(3,Math.round(7+i*2+(seed%9)*0.2))}));}
