import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {Search,Plus,UserPlus,CalendarPlus,Download,Eye,Pencil,Trash2,Phone,Clock3,FlaskConical,FileText,ReceiptText,Check,CheckCircle2,Printer,ArrowLeft,ChevronLeft,ChevronRight,RefreshCw,MoreHorizontal,UserRoundCog,ShieldCheck,ClipboardCheck,Upload,Signature,Wallet,Activity,Stethoscope,Inbox,MessageSquare,ClipboardList,X,Copy,LockKeyhole,CalendarCheck2,Ban,Send,FilePlus2,Edit3} from 'lucide-react';
import {api,downloadFile,uploadFile,fileStorageEnabled} from '../services/api.js';
import {useAuth} from '../app/AuthContext.jsx';
import {Button,Card,PageHeading,Input,Select,Textarea,Field,Modal,StatusBadge,Badge,EmptyState,useToast,ConfirmDialog,Toggle} from '../components/UI.jsx';

const formatCurrency=(v)=>`${Number(v||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})} ج.م`;
const formatDate=(v,withTime=false)=>{if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v).slice(0,10);return new Intl.DateTimeFormat('ar-EG-u-nu-latn',{year:'numeric',month:'short',day:'numeric',...(withTime?{hour:'2-digit',minute:'2-digit'}:{})}).format(d);};
const roleText={admin:'مسؤول النظام',doctor:'طبيب',receptionist:'استقبال',patient:'مريض'};
const typeText={first:'كشف أول',follow_up:'متابعة',consultation:'استشارة',lab:'تحليل'};
const statusTone={normal:'success',out_of_range:'danger',unknown:'neutral',urgent:'danger',normal_priority:'neutral'};

const configs={
 patients:{title:'المرضى',description:'ملفات المرضى والبيانات الأساسية',endpoint:'/patients',add:'مريض جديد',icon:UserPlus,create:'patient',columns:[['fileNo','رقم الملف'],['fullName','اسم المريض'],['sex','الجنس'],['phone','رقم الهاتف'],['status','الحالة'],['createdAt','تاريخ التسجيل']]},
 appointments:{title:'المواعيد',description:'تنظيم المواعيد وحالة الحضور',endpoint:'/appointments',add:'حجز موعد',icon:CalendarPlus,create:'appointment',columns:[['startAt','الوقت'],['patientName','اسم المريض'],['doctorName','الطبيب'],['type','نوع الزيارة'],['status','الحالة']]},
 queue:{title:'قائمة الانتظار',description:'إدارة أدوار اليوم وتحديث الحالة',endpoint:'/queue',add:'إضافة للطابور',icon:Plus,create:'queue',columns:[['number','رقم الدور'],['patientName','المريض'],['doctorName','الطبيب'],['appointmentType','نوع الزيارة'],['arrivedAt','وقت الوصول'],['status','الحالة']]},
 invoices:{title:'الفواتير والمدفوعات',description:'إدارة الفواتير وتسجيل الدفعات يدويًا',endpoint:'/invoices',add:'فاتورة جديدة',icon:ReceiptText,create:'invoice',columns:[['number','رقم الفاتورة'],['patientName','المريض'],['total','الإجمالي'],['paidAmount','المدفوع'],['remaining','المتبقي'],['status','الحالة'],['issuedAt','التاريخ']]},
 labs:{title:'طلبات التحاليل',description:'متابعة العينات والنتائج الطبية',endpoint:'/lab-orders',add:'طلب تحليل جديد',icon:FlaskConical,create:'lab',columns:[['patientName','المريض'],['items','التحاليل'],['priority','الأولوية'],['orderedAt','تاريخ الطلب'],['status','الحالة']]},
 prescriptions:{title:'الروشتات',description:'الروشتات الطبية وحالة التوقيع',endpoint:'/prescriptions',add:'روشتة جديدة',icon:FileText,create:'prescription',columns:[['patientName','المريض'],['diagnosis','التشخيص'],['items','الأدوية'],['issuedAt','التاريخ'],['status','الحالة']]},
 services:{title:'الخدمات الطبية',description:'كتالوج الخدمات والأسعار ومدد الزيارة',endpoint:'/services',add:'إضافة خدمة',icon:Stethoscope,create:'service',columns:[['name','اسم الخدمة'],['price','السعر'],['durationMinutes','المدة'],['color','اللون'],['isActive','الحالة']]},
 'lab-tests':{title:'كتالوج التحاليل',description:'الاختبارات المتاحة والمعدلات المرجعية',endpoint:'/lab-tests?all=true',add:'إضافة نوع تحليل',icon:FlaskConical,create:'lab-test',columns:[['nameAr','اسم التحليل'],['category','الفئة'],['refRange','المعدل المرجعي'],['unit','الوحدة'],['price','السعر'],['turnaroundHours','مدة النتيجة']]},
 medications:{title:'الأدوية',description:'قائمة الأدوية المرجعية والجرعات الشائعة',endpoint:'/medications?all=true',add:'إضافة دواء',icon:FilePlus2,create:'medication',columns:[['nameAr','اسم الدواء'],['brand','العلامة التجارية'],['class','التصنيف'],['commonDoses','الجرعات الشائعة'],['isActive','الحالة']]},
 accounts:{title:'الحسابات',description:'إدارة المستخدمين والأدوار وحالة الحساب',endpoint:'/users',add:'إضافة حساب',icon:UserRoundCog,create:'account',columns:[['fullName','الاسم'],['role','الدور'],['email','البريد الإلكتروني'],['phone','الهاتف'],['status','الحالة'],['lastLoginAt','آخر دخول']]},
 doctors:{title:'الأطباء',description:'الأطباء المسجلون وساعات العمل',endpoint:'/doctors',add:'إضافة طبيب',icon:Stethoscope,create:'account',columns:[['fullName','اسم الطبيب'],['specialty','التخصص'],['email','البريد الإلكتروني'],['phone','الهاتف'],['avgVisitMinutes','مدة الكشف']]},
 notes:{title:'النوتة الطبية',description:'ملاحظات المتابعة المرتبطة بملفات المرضى',endpoint:'/notes',add:'ملاحظة جديدة',icon:Edit3,create:'note',columns:[['title','عنوان الملاحظة'],['patientName','المريض'],['body','المحتوى'],['created_at','التاريخ']]},
 threads:{title:'صندوق الوارد',description:'محادثات المرضى وفريق العيادة',endpoint:'/threads',add:'محادثة جديدة',icon:MessageSquare,create:'thread',columns:[['subject','الموضوع'],['patientName','المريض'],['status','الحالة'],['updated_at','آخر تحديث']]},
 audit:{title:'سجل النشاط',description:'سجل قابل للمراجعة لعمليات الدخول والقراءة والتعديل',endpoint:'/audit',icon:Activity,columns:[['full_name','المستخدم'],['role','الدور'],['action','الإجراء'],['entity','نوع السجل'],['ip','عنوان الاتصال'],['created_at','التاريخ']]}
};

export default function ResourcePage({resource}){
 const cfg=configs[resource]||configs.patients;const location=useLocation();const navigate=useNavigate();const {user}=useAuth();const toast=useToast();const isNew=location.pathname.endsWith('/new');const base=user?.role==='patient'?'/portal':user?.role==='receptionist'?'/reception':`/${user?.role||'admin'}`;const [rows,setRows]=useState([]);const [pagination,setPagination]=useState({page:1,pageSize:20,total:0,pages:1});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [q,setQ]=useState('');const [page,setPage]=useState(1);const [open,setOpen]=useState(false);const [actionTarget,setActionTarget]=useState(null);const [resultModal,setResultModal]=useState(false);const [payModal,setPayModal]=useState(false);const [secret,setSecret]=useState('');const [secretModal,setSecretModal]=useState(false);const [confirm,setConfirm]=useState(null);const [submitting,setSubmitting]=useState(false);const [refreshKey,setRefreshKey]=useState(0);
 const path=`${cfg.endpoint}${cfg.endpoint.includes('?')?'&':'?'}page=${page}&pageSize=20${q?`&q=${encodeURIComponent(q)}`:''}${resource==='doctors'?'&role=doctor':''}`;
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await api(path);setRows(result.data||[]);setPagination(result.pagination||{page:1,pageSize:20,total:(result.data||[]).length,pages:1});}catch(e){setError(e.message);setRows([]);}finally{setLoading(false);}},[path,refreshKey]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{if(isNew){setOpen(true);}else setOpen(false);},[isNew]);
 useEffect(()=>{setPage(1);},[q]);
 const refresh=()=>setRefreshKey(v=>v+1);const closeModal=()=>{setOpen(false);if(isNew)navigate(base+'/'+resource,{replace:true});setActionTarget(null);};
 const creatable={admin:['accounts','doctors','patients','appointments','queue','invoices','labs','prescriptions','services','lab-tests','medications','notes','threads'],doctor:['patients','appointments','queue','labs','prescriptions','notes','threads'],receptionist:['patients','appointments','queue','invoices'],patient:['threads']};const addButton=Boolean(cfg.add&&creatable[user?.role]?.includes(resource));
 const openAdd=()=>{setActionTarget(null);setOpen(true);if(!isNew)navigate(`${base}/${resource}/new`,{replace:false});};
 const runAction=async(kind,row)=>{
  try{
   if(kind==='view'){navigate(`${base}/patients/${row.id}`);return;}
   if(kind==='invoice'){navigate(`${base}/invoices/${row.id}`);return;}
   if(kind==='edit'){setActionTarget(row);setOpen(true);return;}
   if(kind==='pay'){setActionTarget(row);setPayModal(true);return;}
   if(kind==='result'){setActionTarget(row);setResultModal(true);return;}
   if(kind==='thread'){navigate(user.role==='patient'?`/portal/support/${row.id}`:`${base}/inbox/${row.id}`);return;}
   if(kind==='print'){window.print();return;}
   if(kind==='checkin'){await api(`/appointments/${row.id}/check-in`,{method:'POST'});toast('تم تسجيل وصول المريض وإضافته إلى الطابور.');refresh();return;}
   if(kind==='call'||kind==='skip'||kind==='finish'||kind==='remove'){const names={call:'call',skip:'skip',finish:'finish',remove:'remove'};const result=await api(`/queue/${row.id}/${names[kind]}`,{method:'POST'});toast(result.message||'تم تحديث الطابور.');refresh();return;}
   if(kind==='collect'){const result=await api(`/lab-orders/${row.id}/collect-sample`,{method:'POST'});toast(result.message);refresh();return;}
   if(kind==='review'){const result=await api(`/lab-orders/${row.id}/review`,{method:'POST'});toast(result.message);refresh();return;}
   if(kind==='sign'){const result=await api(`/prescriptions/${row.id}/sign`,{method:'POST'});toast(result.message);refresh();return;}
   if(kind==='suspend'||kind==='activate'){const result=await api(`/users/${row.id}/${kind}`,{method:'POST'});toast(result.message);refresh();return;}
   if(kind==='reset'){const result=await api(`/users/${row.id}/reset-password`,{method:'POST'});setSecret(result.temporaryPassword);setSecretModal(true);toast(result.message,'info');refresh();return;}
   if(kind==='archive'){setConfirm({row,kind});return;}
  }catch(e){toast(e.message,'error');}
 };
 const doConfirm=async()=>{if(!confirm)return;setSubmitting(true);try{if(confirm.kind==='archive'&&resource==='patients'){const r=await api(`/patients/${confirm.row.id}`,{method:'DELETE'});toast(r.message);}else if(confirm.kind==='archive'&&resource==='appointments'){const r=await api(`/appointments/${confirm.row.id}/cancel`,{method:'POST'});toast(r.message);}else{const r=await api(`/${resource==='lab-tests'?'lab-tests':resource}/${confirm.row.id}`,{method:'DELETE'});toast(r.message);}setConfirm(null);refresh();}catch(e){toast(e.message,'error');}finally{setSubmitting(false);}};
 const save=async(payload)=>{setSubmitting(true);try{
  const id=actionTarget?.id;let endpoint=cfg.endpoint.split('?')[0];let result;
  if(resource==='doctors')endpoint='/users';
  if(id){result=await api(`${endpoint}/${id}`,{method:'PATCH',body:JSON.stringify(payload)});}else{result=await api(endpoint,{method:'POST',body:JSON.stringify(payload)});}
  toast(result.message||'تم حفظ البيانات بنجاح.');
  if(result.temporaryPassword){setSecret(result.temporaryPassword);setSecretModal(true);}
  closeModal();refresh();
  if(resource==='patients'&&isNew&&result.data?.id)navigate(`${base}/patients/${result.data.id}`);
 }catch(e){toast(e.message,'error');throw e;}finally{setSubmitting(false);}};
 const doPayment=async(payload)=>{setSubmitting(true);try{const result=await api(`/invoices/${actionTarget.id}/payments`,{method:'POST',body:JSON.stringify(payload)});toast(`تم تسجيل الدفعة. المتبقي ${formatCurrency(result.remaining)}.`);setPayModal(false);refresh();}catch(e){toast(e.message,'error');}finally{setSubmitting(false);}};
 const doResult=async(payload)=>{setSubmitting(true);try{const item=payload.item||actionTarget.items?.[0];if(!item){toast('لا يوجد تحليل لإضافة نتيجة له.','error');return;}let fileId=null;if(payload.file){const uploaded=await uploadFile(payload.file,{patientId:actionTarget.patientId,kind:'lab-result'});fileId=uploaded.data.id;}const rawNumber=payload.valueNumber;const value={valueNumber:rawNumber===''||rawNumber==null?null:Number(rawNumber),valueText:payload.valueText||undefined,...(fileId?{fileId}:{})};const result=await api(`/lab-orders/${actionTarget.id}/items/${item.id}/result`,{method:'POST',body:JSON.stringify(value)});toast(result.message);setResultModal(false);refresh();}catch(e){toast(e.message,'error');}finally{setSubmitting(false);}};
 const title=resource==='doctors'&&user?.role==='receptionist'?'الأطباء':cfg.title;
 const actions=addButton?<Button onClick={openAdd} icon={cfg.icon||Plus}>{cfg.add}</Button>:null;
 return <div className="resource-page"><PageHeading eyebrow={user?.role==='admin'?'الإدارة':user?.role==='doctor'?'الرعاية الطبية':'العمليات'} title={title} description={cfg.description} actions={actions}/>
  <div className="resource-stats">{resource==='patients'&&<><MiniMetric title="إجمالي الملفات" value={pagination.total} icon={Users}/><MiniMetric title="ملفات نشطة" value={rows.filter(x=>x.status==='active').length} icon={CheckCircle2}/><MiniMetric title="تحتاج متابعة" value={rows.filter(x=>x.status==='pending').length} icon={Clock3}/></>}{resource==='invoices'&&<><MiniMetric title="عدد الفواتير" value={pagination.total} icon={ReceiptText}/><MiniMetric title="مدفوع" value={rows.filter(x=>x.status==='paid').length} icon={CheckCircle2}/><MiniMetric title="غير مسدد" value={rows.filter(x=>['unpaid','partial'].includes(x.status)).length} icon={Wallet}/></>}{resource==='appointments'&&<><MiniMetric title="المواعيد الظاهرة" value={pagination.total} icon={CalendarCheck2}/><MiniMetric title="مؤكدة" value={rows.filter(x=>x.status==='confirmed').length} icon={CheckCircle2}/><MiniMetric title="قيد الانتظار" value={rows.filter(x=>x.status==='pending').length} icon={Clock3}/></>}{resource==='labs'&&<><MiniMetric title="طلبات التحليل" value={pagination.total} icon={FlaskConical}/><MiniMetric title="نتائج جاهزة" value={rows.filter(x=>x.status==='result_ready').length} icon={CheckCircle2}/><MiniMetric title="عينات جديدة" value={rows.filter(x=>x.status==='new').length} icon={Clock3}/></>}</div>
  <Card className="table-card"><div className="table-toolbar"><div className="table-toolbar-title"><div className="table-title-icon"><cfg.icon size={19}/></div><div><b>{title}</b><small>{pagination.total||0} سجل</small></div></div><div className="table-controls"><div className="table-search"><Search size={16}/><input placeholder="ابحث في السجلات..." value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button onClick={()=>setQ('')}><X size={14}/></button>}</div><Button variant="ghost" size="sm" icon={RefreshCw} onClick={refresh} title="تحديث" aria-label="تحديث" className="refresh-button">تحديث</Button>{['patients','invoices','appointments','audit'].includes(resource)&&<Button variant="outline" size="sm" icon={Download} onClick={()=>downloadFile(`/reports/export?type=${resource==='appointments'?'appointments':resource==='invoices'?'invoices':resource==='audit'?'audit':'patients'}`,`${resource}.csv`).catch(e=>toast(e.message,'error'))}>تصدير</Button>}</div></div>
   {error&&<div className="table-error"><span>{error}</span><Button variant="outline" size="sm" onClick={load}>إعادة المحاولة</Button></div>}
   {loading?<div className="skeleton-table">{[1,2,3,4,5].map(x=><i key={x}/>)}</div>:rows.length?<><div className="table-wrap"><table className="data-table"><thead><tr>{cfg.columns.map(([key,label])=><th key={key}>{label}</th>)}<th>الإجراءات</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{cfg.columns.map(([key])=><td key={key}>{renderCell(resource,key,row)}</td>)}<td><div className="row-actions">{actionsFor(resource,row,user).map(a=><button key={a.kind} className={`row-action ${a.tone||''}`} title={a.label} aria-label={a.label} onClick={()=>runAction(a.kind,row)}><a.icon size={16}/></button>)}</div></td></tr>)}</tbody></table></div><div className="table-pagination"><span>عرض {rows.length} من {pagination.total||rows.length} سجل</span><div><button disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))}><ChevronRight size={16}/></button><span>{page} / {Math.max(1,pagination.pages||1)}</span><button disabled={page>=(pagination.pages||1)} onClick={()=>setPage(v=>v+1)}><ChevronLeft size={16}/></button></div></div></>:<EmptyState icon={cfg.icon} title={q?'لا توجد نتائج مطابقة':'لا توجد سجلات بعد'} description={q?'جرّب كلمة بحث مختلفة.':'أضف سجلًا جديدًا للبدء.'} action={addButton&&<Button size="sm" onClick={openAdd} icon={Plus}>{cfg.add}</Button>}/>}
  </Card>
  <ResourceModal open={open} onClose={closeModal} title={actionTarget?`تعديل ${resource==='doctors'?'بيانات الطبيب':resource==='accounts'?'الحساب':title}`:cfg.add||`إضافة ${title}`} type={cfg.create} resource={resource} initial={actionTarget} onSave={save} loading={submitting}/>
  <PaymentModal open={payModal} onClose={()=>setPayModal(false)} invoice={actionTarget} onSave={doPayment} loading={submitting}/>
  <ResultModal open={resultModal} onClose={()=>setResultModal(false)} order={actionTarget} onSave={doResult} loading={submitting}/>
  <Modal open={secretModal} onClose={()=>setSecretModal(false)} title="كلمة مرور مؤقتة" width="sm" footer={<Button onClick={()=>setSecretModal(false)}>تم</Button>}><div className="secret-panel"><ShieldCheck size={22}/><p>احتفظ بكلمة المرور وأرسلها للمستخدم عبر قناة آمنة. سيتم طلب تغييرها عند أول دخول.</p><div className="secret-value"><code>{secret}</code><button onClick={()=>navigator.clipboard?.writeText(secret).then(()=>toast('تم نسخ كلمة المرور.'))}><Copy size={15}/> نسخ</button></div></div></Modal>
  <ConfirmDialog open={Boolean(confirm)} title="تأكيد الإجراء" message={resource==='patients'?'سيتم أرشفة ملف المريض مع الاحتفاظ بالسجل الطبي.':'سيتم إيقاف هذا العنصر دون حذف السجلات المرتبطة.'} onCancel={()=>setConfirm(null)} onConfirm={doConfirm} confirmLabel="تأكيد" danger loading={submitting}/>
 </div>;
}

function MiniMetric({title,value,icon:Icon}){return <div className="mini-metric"><span className="mini-metric-icon"><Icon size={17}/></span><span><small>{title}</small><b>{value??0}</b></span></div>}
function renderCell(resource,key,row){
 if(key==='status')return <StatusBadge status={row.status}/>;
 if(key==='role')return <Badge tone={row.role==='admin'?'violet':row.role==='doctor'?'teal':row.role==='patient'?'aqua':'info'}>{roleText[row.role]||row.role}</Badge>;
 if(key==='type')return <Badge tone="teal">{typeText[row.type]||row.type}</Badge>;
 if(key==='appointmentType')return <Badge tone="aqua">{typeText[row.appointmentType]||'زيارة'}</Badge>;
 if(key==='priority')return <Badge tone={row.priority==='urgent'?'danger':'neutral'}>{row.priority==='urgent'?'عاجل':'عادي'}</Badge>;
 if(key==='total'||key==='paidAmount'||key==='remaining'||key==='price')return formatCurrency(row[key]);
 if(key==='durationMinutes'||key==='avgVisitMinutes'||key==='turnaroundHours')return <span>{row[key]} {key==='turnaroundHours'?'ساعة':'دقيقة'}</span>;
 if(key==='items'){const items=row.items||[];return <div className="chips-cell">{items.length?items.slice(0,2).map(x=><Badge key={x.id||x.name_snapshot||x.lab_test_id} tone={x.flag==='out_of_range'?'danger':'neutral'}>{x.name_ar||x.name_snapshot}</Badge>):'—'}{items.length>2&&<span className="muted">+{items.length-2}</span>}</div>}
 if(key==='refRange')return <span>{row.refText||`${row.refMin??'—'} – ${row.refMax??'—'}`}</span>;
 if(key==='commonDoses')return <span className="cell-truncate">{Array.isArray(row.commonDoses)?row.commonDoses.join('، '):row.commonDoses||'—'}</span>;
 if(key==='sex')return row.sex==='female'?'أنثى':row.sex==='male'?'ذكر':'غير محدد';
 if(key==='isActive')return <StatusBadge status={row.isActive?'active':'suspended'}/>;
 if(key==='color')return <span className="color-cell"><i style={{background:row.color}}/>{row.color}</span>;
 if(key==='action')return row.action;
 if(key==='created_at'||key==='updated_at'||key==='createdAt'||key==='issuedAt'||key==='orderedAt'||key==='startAt'||key==='lastLoginAt'||key==='arrivedAt')return <span className="date-cell">{formatDate(row[key],['startAt','arrivedAt'].includes(key))}</span>;
 if(key==='fullName')return <span className="name-cell"><span className="avatar-mini">{String(row.fullName||'م').slice(0,1)}</span><span><b>{row.fullName}</b><small>{row.fileNo||row.specialty||''}</small></span></span>;
 if(key==='patientName')return <span className="name-cell"><span className="avatar-mini">{String(row.patientName||'م').slice(0,1)}</span><b>{row.patientName}</b></span>;
 const val=row[key];if(val==null||val==='')return '—';return <span className={typeof val==='string'&&val.length>70?'cell-truncate':''}>{String(val)}</span>;
}
function actionsFor(resource,row,user){const a=[];if(resource==='patients'){a.push({kind:'view',label:'فتح الملف',icon:Eye},{kind:'edit',label:'تعديل',icon:Pencil});if(user.role==='admin'||user.role==='receptionist')a.push({kind:'archive',label:'أرشفة',icon:Trash2,tone:'danger'});}
 else if(resource==='accounts'||resource==='doctors'){if(resource==='accounts')a.push({kind:'edit',label:'تعديل الحساب',icon:Pencil},{kind:row.status==='active'?'suspend':'activate',label:row.status==='active'?'إيقاف الحساب':'تفعيل الحساب',icon:row.status==='active'?Ban:CheckCircle2,tone:row.status==='active'?'danger':'success'},{kind:'reset',label:'إعادة تعيين كلمة المرور',icon:LockKeyhole});else if(user.role==='admin')a.push({kind:'edit',label:'تعديل بيانات الطبيب',icon:Pencil});}
 else if(resource==='appointments'){a.push({kind:'checkin',label:'تسجيل الوصول',icon:CheckCircle2,tone:'success'},{kind:'edit',label:'تعديل الموعد',icon:Pencil});if(!['cancelled','completed'].includes(row.status))a.push({kind:'archive',label:'إلغاء الموعد',icon:Ban,tone:'danger'});}
 else if(resource==='queue'){if(row.status==='waiting')a.push({kind:'call',label:'نداء',icon:Phone,tone:'success'},{kind:'skip',label:'تخطي',icon:ChevronLeft});if(['called','in_visit'].includes(row.status))a.push({kind:'finish',label:'إنهاء الكشف',icon:CheckCircle2,tone:'success'});if(['waiting','skipped'].includes(row.status))a.push({kind:'remove',label:'إزالة',icon:Trash2,tone:'danger'});}
 else if(resource==='labs'){if(row.status==='new')a.push({kind:'collect',label:'تسجيل سحب العينة',icon:Check});if(['sample_collected','new'].includes(row.status))a.push({kind:'result',label:'إضافة نتيجة',icon:Upload,tone:'info'});if(row.status==='result_ready'&&user.role==='doctor')a.push({kind:'review',label:'مراجعة النتيجة',icon:Eye,tone:'success'});}
 else if(resource==='prescriptions'){a.push({kind:'print',label:'طباعة الروشتة',icon:Printer});if(row.status==='draft'&&user.role==='doctor')a.push({kind:'sign',label:'توقيع الروشتة',icon:Signature,tone:'success'});}
 else if(resource==='invoices'){a.push({kind:'invoice',label:'عرض تفاصيل الفاتورة',icon:Eye});if(row.status==='unpaid'||row.status==='partial')a.push({kind:'pay',label:'تسجيل دفعة',icon:Wallet,tone:'success'});}
 else if(resource==='services'||resource==='lab-tests'||resource==='medications')a.push({kind:'edit',label:'تعديل',icon:Pencil},{kind:'archive',label:'إيقاف',icon:Trash2,tone:'danger'});
 else if(resource==='threads')a.push({kind:'thread',label:'فتح المحادثة',icon:MessageSquare});
 return a;}

function ResourceModal({open,onClose,title,type,resource,initial,onSave,loading}){const [deps,setDeps]=useState({patients:[],doctors:[],services:[],tests:[],medications:[]});useEffect(()=>{if(!open)return;Promise.all([api('/patients?pageSize=100').catch(()=>({data:[]})),api('/doctors').catch(()=>({data:[]})),api('/services').catch(()=>({data:[]})),api('/lab-tests').catch(()=>({data:[]})),api('/medications').catch(()=>({data:[]}))]).then(([p,d,s,t,m])=>setDeps({patients:p.data||[],doctors:d.data||[],services:s.data||[],tests:t.data||[],medications:m.data||[]}));},[open]);return <Modal open={open} onClose={onClose} title={title} width={type==='patient'?'lg':'md'}><FormContent type={type} resource={resource} initial={initial} deps={deps} onSave={onSave} loading={loading} onCancel={onClose}/></Modal>}

function FormContent({type,resource,initial,deps,onSave,loading,onCancel}){const toast=useToast();const [value,setValue]=useState({});const [file,setFile]=useState(null);useEffect(()=>{if(!initial){setValue({role:resource==='doctors'?'doctor':'receptionist',type:'first',sex:'unspecified',status:'active',durationMinutes:30,turnaroundHours:24,quantity:1,priority:'normal'});return;}const v={...initial};for(const [a,b] of Object.entries({firstName:'first_name',lastName:'last_name',patientId:'patient_id',doctorId:'doctor_id',serviceId:'service_id',startAt:'start_at',endAt:'end_at',nameAr:'name_ar',nameEn:'name_en',refMin:'ref_min',refMax:'ref_max',refText:'ref_text',durationMinutes:'duration_minutes',turnaroundHours:'turnaround_hours',fullName:'full_name',avgVisitMinutes:'avg_visit_minutes',commonDoses:'common_doses'}))if(v[a]===undefined&&v[b]!==undefined)v[a]=v[b];setValue(v);},[initial,resource]);const set=(k,v)=>setValue(s=>({...s,[k]:v}));
 const submit=async(e)=>{e.preventDefault();let data={...value};
  if(type==='patient'){const payload={firstName:data.firstName,lastName:data.lastName,dob:data.dob||null,sex:data.sex||'unspecified',phone:data.phone||null,email:data.email||'',address:data.address||'',emergencyContactName:data.emergencyContactName||'',emergencyContactPhone:data.emergencyContactPhone||'',allergies:data.allergies||'',chronicConditions:data.chronicConditions||'',currentMedications:data.currentMedications||'',initialNotes:data.initialNotes||''};await onSave(payload);return;}
  if(type==='account'){const payload={fullName:data.fullName,role:data.role,email:data.email||'',phone:data.phone||'',...(data.password?{password:data.password}:{}),...(data.role==='doctor'?{specialty:data.specialty||'طب الأسرة',avgVisitMinutes:Number(data.avgVisitMinutes||15)}:{})};await onSave(payload);return;}
  if(type==='appointment'){const start=new Date(data.startAt).toISOString();const end=data.endAt?new Date(data.endAt).toISOString():new Date(new Date(start).getTime()+30*60000).toISOString();await onSave({patientId:Number(data.patientId),doctorId:Number(data.doctorId),serviceId:data.serviceId?Number(data.serviceId):null,type:data.type||'first',startAt:start,endAt:end,reason:data.reason||'',notes:data.notes||''});return;}
  if(type==='queue'){await onSave({patientId:Number(data.patientId),doctorId:Number(data.doctorId)});return;}
  if(type==='service'){await onSave({name:data.name,price:Number(data.price),durationMinutes:Number(data.durationMinutes),color:data.color||'#0f7778',isActive:true});return;}
  if(type==='lab-test'){await onSave({nameAr:data.nameAr,nameEn:data.nameEn||'',category:data.category||'',unit:data.unit||'',refMin:data.refMin===''?null:Number(data.refMin),refMax:data.refMax===''?null:Number(data.refMax),refText:data.refText||'',price:Number(data.price),turnaroundHours:Number(data.turnaroundHours||24),isActive:true});return;}
  if(type==='medication'){const commonDoses=String(data.commonDoses||'').split(/[,،]/).map(x=>x.trim()).filter(Boolean);await onSave({nameAr:data.nameAr,nameEn:data.nameEn||'',brand:data.brand||'',class:data.class||'',commonDoses,isActive:true});return;}
  if(type==='invoice'){await onSave({patientId:Number(data.patientId),dueAt:data.dueAt||null,items:[{description:data.description||'خدمة طبية',quantity:Number(data.quantity||1),unitPrice:Number(data.unitPrice||0)}]});return;}
  if(type==='lab'){const ids=Array.isArray(data.testIds)?data.testIds.map(Number):[Number(data.testId)].filter(Boolean);await onSave({patientId:Number(data.patientId),priority:data.priority||'normal',reason:data.reason||'',testIds:ids});return;}
  if(type==='prescription'){const items=[{medicationId:data.medicationId?Number(data.medicationId):null,name:data.name||data.medicationName,dose:data.dose||'',frequency:data.frequency||'',route:data.route||'فموي',duration:data.duration||'',instructions:data.instructions||''}];await onSave({patientId:Number(data.patientId),diagnosis:data.diagnosis||'',recommendations:data.recommendations||'',items});return;}
  if(type==='note'){await onSave({patientId:Number(data.patientId),title:data.title||'ملاحظة طبية',body:data.body||''});return;}
  if(type==='thread'){const payload={subject:data.subject||'استفسار جديد',body:data.body||'',...(data.patientId?{patientId:Number(data.patientId)}:{})};await onSave(payload);return;}
  await onSave(data);
 };
 const patientOptions=deps.patients.map(p=><option key={p.id} value={p.id}>{p.fullName} — {p.fileNo}</option>);const doctorOptions=deps.doctors.map(d=><option key={d.id} value={d.id}>{d.fullName} — {d.specialty||'طبيب'}</option>);
 return <form className="resource-form" onSubmit={submit}>
 {type==='patient'&&<><div className="form-section-title"><b>البيانات الأساسية</b><small>الحقول المعلّمة بعلامة * مطلوبة</small></div><div className="form-grid two"><Field label="الاسم الأول" required><Input value={value.firstName||''} onChange={e=>set('firstName',e.target.value)} required/></Field><Field label="اسم العائلة" required><Input value={value.lastName||''} onChange={e=>set('lastName',e.target.value)} required/></Field><Field label="تاريخ الميلاد"><Input type="date" value={value.dob||''} onChange={e=>set('dob',e.target.value)}/></Field><Field label="الجنس"><Select value={value.sex||'unspecified'} onChange={e=>set('sex',e.target.value)}><option value="unspecified">غير محدد</option><option value="female">أنثى</option><option value="male">ذكر</option></Select></Field><Field label="رقم الهاتف"><Input value={value.phone||''} onChange={e=>set('phone',e.target.value)} inputMode="tel"/></Field><Field label="البريد الإلكتروني"><Input type="email" value={value.email||''} onChange={e=>set('email',e.target.value)}/></Field></div><Field label="العنوان"><Input value={value.address||''} onChange={e=>set('address',e.target.value)}/></Field><div className="form-section-title"><b>البيانات الطبية الأولية</b><small>يمكن تحديثها من الملف الطبي</small></div><div className="form-grid two"><Field label="الحساسية"><Input value={value.allergies||''} onChange={e=>set('allergies',e.target.value)} placeholder="مثال: البنسلين"/></Field><Field label="الأمراض المزمنة"><Input value={value.chronicConditions||''} onChange={e=>set('chronicConditions',e.target.value)}/></Field><Field label="الأدوية الحالية"><Input value={value.currentMedications||''} onChange={e=>set('currentMedications',e.target.value)}/></Field><Field label="جهة اتصال للطوارئ"><Input value={value.emergencyContactName||''} onChange={e=>set('emergencyContactName',e.target.value)}/></Field><Field label="هاتف الطوارئ"><Input value={value.emergencyContactPhone||''} onChange={e=>set('emergencyContactPhone',e.target.value)}/></Field></div><Field label="ملاحظات أولية"><Textarea rows={3} value={value.initialNotes||''} onChange={e=>set('initialNotes',e.target.value)}/></Field></>}
 {type==='account'&&<><div className="form-grid two"><Field label="الاسم الكامل" required><Input value={value.fullName||''} onChange={e=>set('fullName',e.target.value)} required/></Field><Field label="الدور" required><Select value={value.role||'receptionist'} onChange={e=>set('role',e.target.value)}><option value="doctor">طبيب</option><option value="receptionist">موظف استقبال</option><option value="patient">مريض</option><option value="admin">مسؤول النظام</option></Select></Field><Field label="البريد الإلكتروني"><Input type="email" value={value.email||''} onChange={e=>set('email',e.target.value)}/></Field><Field label="رقم الهاتف"><Input value={value.phone||''} onChange={e=>set('phone',e.target.value)}/></Field></div>{value.role==='doctor'&&<div className="form-grid two"><Field label="التخصص"><Input value={value.specialty||''} onChange={e=>set('specialty',e.target.value)}/></Field><Field label="متوسط مدة الكشف (دقيقة)"><Input type="number" min="5" value={value.avgVisitMinutes||15} onChange={e=>set('avgVisitMinutes',e.target.value)}/></Field></div>}<Field label="كلمة مرور مؤقتة" help="اتركها فارغة لإنشاء كلمة مؤقتة عشوائية تُعرض مرة واحدة."><Input type="password" value={value.password||''} onChange={e=>set('password',e.target.value)} minLength={8}/></Field><div className="form-hint"><ShieldCheck size={16}/> الحساب يُفعّل فور الحفظ. إذا أُنشئت كلمة مؤقتة، يجب على المستخدم تغييرها عند أول دخول.</div></>}
 {type==='appointment'&&<><div className="form-grid two"><Field label="المريض" required><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)} required><option value="">اختر المريض</option>{patientOptions}</Select></Field><Field label="الطبيب" required><Select value={value.doctorId||''} onChange={e=>set('doctorId',e.target.value)} required><option value="">اختر الطبيب</option>{doctorOptions}</Select></Field><Field label="الخدمة"><Select value={value.serviceId||''} onChange={e=>set('serviceId',e.target.value)}><option value="">اختر الخدمة (اختياري)</option>{deps.services.map(s=><option value={s.id} key={s.id}>{s.name} — {formatCurrency(s.price)}</option>)}</Select></Field><Field label="نوع الموعد"><Select value={value.type||'first'} onChange={e=>set('type',e.target.value)}><option value="first">كشف أول</option><option value="follow_up">متابعة</option><option value="consultation">استشارة</option><option value="lab">تحليل</option></Select></Field><Field label="وقت البداية" required><Input type="datetime-local" value={value.startAt||''} onChange={e=>{const s=e.target.value;set('startAt',s);if(s&&!value.endAt){const d=new Date(s);d.setMinutes(d.getMinutes()+30);set('endAt',`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`);}}} required/></Field><Field label="وقت الانتهاء" required><Input type="datetime-local" value={value.endAt||''} onChange={e=>set('endAt',e.target.value)} required/></Field></div><Field label="سبب الزيارة"><Input value={value.reason||''} onChange={e=>set('reason',e.target.value)} placeholder="اكتب سبب الزيارة"/></Field><Field label="ملاحظات"><Textarea rows={3} value={value.notes||''} onChange={e=>set('notes',e.target.value)}/></Field><div className="form-hint"><Clock3 size={16}/> يتحقق النظام من تعارض المواعيد قبل الحفظ.</div></>}
 {type==='queue'&&<div className="form-grid two"><Field label="المريض" required><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)} required><option value="">اختر المريض</option>{patientOptions}</Select></Field><Field label="الطبيب" required><Select value={value.doctorId||''} onChange={e=>set('doctorId',e.target.value)} required><option value="">اختر الطبيب</option>{doctorOptions}</Select></Field></div>}
 {type==='service'&&<div className="form-grid two"><Field label="اسم الخدمة" required><Input value={value.name||''} onChange={e=>set('name',e.target.value)} required/></Field><Field label="السعر (ج.م)" required><Input type="number" min="0" step="0.01" value={value.price??''} onChange={e=>set('price',e.target.value)} required/></Field><Field label="المدة (دقيقة)" required><Input type="number" min="5" value={value.durationMinutes||30} onChange={e=>set('durationMinutes',e.target.value)} required/></Field><Field label="لون الخدمة"><Input type="color" value={value.color||'#0f7778'} onChange={e=>set('color',e.target.value)}/></Field></div>}
 {type==='lab-test'&&<div className="form-grid two"><Field label="الاسم بالعربية" required><Input value={value.nameAr||''} onChange={e=>set('nameAr',e.target.value)} required/></Field><Field label="الاسم بالإنجليزية"><Input value={value.nameEn||''} onChange={e=>set('nameEn',e.target.value)}/></Field><Field label="الفئة"><Input value={value.category||''} onChange={e=>set('category',e.target.value)}/></Field><Field label="الوحدة"><Input value={value.unit||''} onChange={e=>set('unit',e.target.value)}/></Field><Field label="الحد الأدنى المرجعي"><Input type="number" step="0.001" value={value.refMin??''} onChange={e=>set('refMin',e.target.value)}/></Field><Field label="الحد الأعلى المرجعي"><Input type="number" step="0.001" value={value.refMax??''} onChange={e=>set('refMax',e.target.value)}/></Field><Field label="المعدل المرجعي كنص"><Input value={value.refText||''} onChange={e=>set('refText',e.target.value)} placeholder="مثال: حسب العمر والجنس"/></Field><Field label="السعر (ج.م)"><Input type="number" min="0" step="0.01" value={value.price??''} onChange={e=>set('price',e.target.value)}/></Field><Field label="مدة ظهور النتيجة (ساعة)"><Input type="number" min="1" value={value.turnaroundHours||24} onChange={e=>set('turnaroundHours',e.target.value)}/></Field></div>}
 {type==='medication'&&<div className="form-grid two"><Field label="اسم الدواء بالعربية" required><Input value={value.nameAr||''} onChange={e=>set('nameAr',e.target.value)} required/></Field><Field label="الاسم بالإنجليزية"><Input value={value.nameEn||''} onChange={e=>set('nameEn',e.target.value)}/></Field><Field label="العلامة التجارية"><Input value={value.brand||''} onChange={e=>set('brand',e.target.value)}/></Field><Field label="التصنيف"><Input value={value.class||''} onChange={e=>set('class',e.target.value)}/></Field><Field label="الجرعات الشائعة" className="full-span"><Input value={Array.isArray(value.commonDoses)?value.commonDoses.join('، '):value.commonDoses||''} onChange={e=>set('commonDoses',e.target.value)} placeholder="500 mg، 1 g"/></Field></div>}
 {type==='invoice'&&<><div className="form-grid two"><Field label="المريض" required><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)} required><option value="">اختر المريض</option>{patientOptions}</Select></Field><Field label="تاريخ الاستحقاق"><Input type="date" value={value.dueAt||''} onChange={e=>set('dueAt',e.target.value)}/></Field></div><div className="form-section-title"><b>بند الفاتورة</b><small>أضف الخدمة والمبلغ</small></div><Field label="وصف الخدمة" required><Input value={value.description||''} onChange={e=>set('description',e.target.value)} placeholder="كشف طبي" required/></Field><div className="form-grid two"><Field label="الكمية"><Input type="number" min="1" value={value.quantity||1} onChange={e=>set('quantity',e.target.value)}/></Field><Field label="سعر الوحدة (ج.م)" required><Input type="number" min="0" step="0.01" value={value.unitPrice??''} onChange={e=>set('unitPrice',e.target.value)} required/></Field></div></>}
 {type==='lab'&&<><div className="form-grid two"><Field label="المريض" required><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)} required><option value="">اختر المريض</option>{patientOptions}</Select></Field><Field label="الأولوية"><Select value={value.priority||'normal'} onChange={e=>set('priority',e.target.value)}><option value="normal">عادي</option><option value="urgent">عاجل</option></Select></Field></div><Field label="التحاليل المطلوبة" required><div className="checkbox-list">{deps.tests.map(t=><label key={t.id}><input type="checkbox" checked={(value.testIds||[]).includes(String(t.id))||(value.testIds||[]).includes(t.id)} onChange={e=>set('testIds',e.target.checked?[...(value.testIds||[]),t.id]:(value.testIds||[]).filter(x=>Number(x)!==Number(t.id)))}/><span>{t.nameAr}</span><small>{formatCurrency(t.price)}</small></label>)}</div></Field><Field label="سبب الطلب"><Textarea rows={3} value={value.reason||''} onChange={e=>set('reason',e.target.value)} placeholder="الشك / المتابعة السريرية"/></Field></>}
 {type==='prescription'&&<><div className="form-grid two"><Field label="المريض" required><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)} required><option value="">اختر المريض</option>{patientOptions}</Select></Field><Field label="التشخيص"><Input value={value.diagnosis||''} onChange={e=>set('diagnosis',e.target.value)}/></Field></div><Field label="الدواء" required><Select value={value.medicationId||''} onChange={e=>{set('medicationId',e.target.value);const med=deps.medications.find(x=>String(x.id)===e.target.value);if(med){set('name',med.nameAr);set('dose',med.commonDoses?.[0]||'');}}} required><option value="">اختر من قائمة الأدوية</option>{deps.medications.map(m=><option key={m.id} value={m.id}>{m.nameAr} {m.brand?`— ${m.brand}`:''}</option>)}</Select></Field><div className="form-grid two"><Field label="الجرعة"><Input value={value.dose||''} onChange={e=>set('dose',e.target.value)}/></Field><Field label="التكرار"><Input value={value.frequency||''} onChange={e=>set('frequency',e.target.value)} placeholder="كل 8 ساعات"/></Field><Field label="طريقة الاستخدام"><Input value={value.route||'فموي'} onChange={e=>set('route',e.target.value)}/></Field><Field label="المدة"><Input value={value.duration||''} onChange={e=>set('duration',e.target.value)} placeholder="5 أيام"/></Field></div><Field label="تعليمات إضافية"><Textarea rows={2} value={value.instructions||''} onChange={e=>set('instructions',e.target.value)}/></Field><Field label="توصيات الطبيب"><Textarea rows={3} value={value.recommendations||''} onChange={e=>set('recommendations',e.target.value)}/></Field><div className="form-hint"><ShieldCheck size={16}/> ستبقى الروشتة مسودة حتى توقّعها.</div></>}
 {type==='note'&&<><Field label="المريض" required><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)} required><option value="">اختر المريض</option>{patientOptions}</Select></Field><Field label="عنوان الملاحظة"><Input value={value.title||''} onChange={e=>set('title',e.target.value)}/></Field><Field label="الملاحظة" required><Textarea rows={7} value={value.body||''} onChange={e=>set('body',e.target.value)} required/></Field></>}
 {type==='thread'&&<><Field label="المريض"><Select value={value.patientId||''} onChange={e=>set('patientId',e.target.value)}><option value="">المريض المرتبط بحسابك</option>{patientOptions}</Select></Field><Field label="عنوان المحادثة"><Input value={value.subject||''} onChange={e=>set('subject',e.target.value)}/></Field><Field label="الرسالة الأولى" required><Textarea rows={5} value={value.body||''} onChange={e=>set('body',e.target.value)} required/></Field></>}
 <div className="modal-form-actions"><Button variant="ghost" type="button" onClick={onCancel}>إلغاء</Button><Button type="submit" loading={loading}>حفظ</Button></div>
 </form>;
}

function PaymentModal({open,onClose,invoice,onSave,loading}){const [form,setForm]=useState({amount:'',method:'cash',paidAt:new Date().toISOString().slice(0,10),reference:''});useEffect(()=>{if(invoice)setForm({amount:String(Number(invoice.remaining||Number(invoice.total)-Number(invoice.paidAmount))),method:'cash',paidAt:new Date().toISOString().slice(0,10),reference:''});},[invoice]);return <Modal open={open} onClose={onClose} title="تسجيل دفعة" width="sm">{invoice&&<form className="resource-form" onSubmit={e=>{e.preventDefault();onSave({...form,amount:Number(form.amount),paidAt:form.paidAt?new Date(form.paidAt).toISOString():undefined});}}><div className="invoice-summary"><b>{invoice.number}</b><span>{invoice.patientName}</span><small>الرصيد المتبقي: <strong>{formatCurrency(invoice.remaining??Number(invoice.total)-Number(invoice.paidAmount))}</strong></small></div><Field label="مبلغ الدفعة (ج.م)" required><Input type="number" min="0.01" max={invoice.remaining??Number(invoice.total)-Number(invoice.paidAmount)} step="0.01" value={form.amount} onChange={e=>setForm(v=>({...v,amount:e.target.value}))} required/></Field><Field label="طريقة الدفع"><Select value={form.method} onChange={e=>setForm(v=>({...v,method:e.target.value}))}><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="wallet">محفظة إلكترونية</option></Select></Field><Field label="التاريخ"><Input type="date" value={form.paidAt} onChange={e=>setForm(v=>({...v,paidAt:e.target.value}))}/></Field><Field label="رقم مرجعي (اختياري)"><Input value={form.reference} onChange={e=>setForm(v=>({...v,reference:e.target.value}))}/></Field><div className="modal-form-actions"><Button variant="ghost" type="button" onClick={onClose}>إلغاء</Button><Button type="submit" loading={loading}>تأكيد الدفع</Button></div></form>}</Modal>}
function ResultModal({open,onClose,order,onSave,loading}){const [form,setForm]=useState({item:'',valueNumber:'',valueText:''});useEffect(()=>{if(order)setForm({item:order.items?.[0]||null,valueNumber:'',valueText:''});},[order]);return <Modal open={open} onClose={onClose} title="إضافة نتيجة تحليل" width="sm">{order&&<form className="resource-form" onSubmit={e=>{e.preventDefault();onSave(form);}}><div className="invoice-summary"><b>{order.patientName}</b><span>{order.fileNo}</span><small>{fileStorageEnabled?'اختر التحليل وأدخل النتيجة أو أرفق تقريرًا.':'اختر التحليل وأدخل النتيجة.'}</small></div><Field label="التحليل"><Select value={form.item?.id||''} onChange={e=>setForm(v=>({...v,item:order.items.find(x=>String(x.id)===e.target.value)}))}>{order.items?.map(i=><option key={i.id} value={i.id}>{i.name_ar} {i.unit?`(${i.unit})`:''}</option>)}</Select></Field><Field label="القيمة الرقمية"><Input type="number" step="any" value={form.valueNumber} onChange={e=>setForm(v=>({...v,valueNumber:e.target.value}))}/></Field><Field label="القيمة النصية"><Input value={form.valueText} onChange={e=>setForm(v=>({...v,valueText:e.target.value}))}/></Field>{fileStorageEnabled&&<Field label="تقرير PDF أو صورة"><input className="file-input" type="file" accept=".pdf,image/png,image/jpeg,image/webp" onChange={e=>setForm(v=>({...v,file:e.target.files?.[0]||null}))}/></Field>}<div className="modal-form-actions"><Button variant="ghost" type="button" onClick={onClose}>إلغاء</Button><Button type="submit" loading={loading}>حفظ النتيجة</Button></div></form>}</Modal>}

export function PatientFilePage({patientId}){const {user}=useAuth();const toast=useToast();const navigate=useNavigate();const [patient,setPatient]=useState(null);const [timeline,setTimeline]=useState([]);const [loading,setLoading]=useState(true);const [tab,setTab]=useState('overview');const [editing,setEditing]=useState(false);const [medical,setMedical]=useState({});const prefix=user?.role==='patient'?'/portal':user?.role==='receptionist'?'/reception':`/${user?.role}`;
 useEffect(()=>{let ok=true;setLoading(true);Promise.all([api(`/patients/${patientId}`),api(`/patients/${patientId}/timeline`)]).then(([p,t])=>{if(!ok)return;setPatient(p.data);setMedical(p.data?.medical||{});setTimeline(t.data||[]);}).catch(e=>toast(e.message,'error')).finally(()=>ok&&setLoading(false));return()=>{ok=false;};},[patientId]);
 if(loading)return <div className="profile-skeleton"><i/><i/><i/></div>;if(!patient)return <EmptyState title="لم يتم العثور على الملف" description="تحقق من رقم الملف أو الصلاحيات."/>;
 const tabs=[['overview','نظرة عامة'],['visits','الزيارات'],['appointments','المواعيد'],['labs','التحاليل'],['prescriptions','الروشتات'],['notes','الملاحظات'],['history','التاريخ الكامل']];const list=tab==='overview'?timeline.slice(0,4):timeline.filter(x=>tab==='visits'?x.kind==='visit':tab==='appointments'?x.kind==='appointment':tab==='labs'?x.kind==='lab':tab==='prescriptions'?x.kind==='prescription':tab==='notes'?x.kind==='note':true);
 const saveMedical=async()=>{try{await api(`/patients/${patient.id}/medical`,{method:'PATCH',body:JSON.stringify(medical)});setEditing(false);toast('تم حفظ البيانات الطبية.');const p=await api(`/patients/${patient.id}`);setPatient(p.data);}catch(e){toast(e.message,'error');}};
 return <div className="patient-file-page"><PageHeading eyebrow="ملف المريض" title={patient.fullName} description={`رقم الملف ${patient.fileNo} · ${patient.sex==='female'?'أنثى':patient.sex==='male'?'ذكر':'غير محدد'} · ${patient.phone||'لا يوجد هاتف'}`} actions={<><Button variant="outline" icon={CalendarPlus} onClick={()=>navigate(`${prefix}/appointments/new`)}>موعد جديد</Button>{user.role!=='patient'&&<Button icon={Stethoscope} onClick={()=>navigate(`${prefix}/visits/new?patient=${patient.id}`)}>كشف جديد</Button>}</>}/>
 <Card className="patient-profile-banner"><div className="profile-avatar-large">{patient.firstName?.slice(0,1)}</div><div className="profile-banner-text"><div className="profile-name-row"><h2>{patient.fullName}</h2>{patient.medical?.allergyFlag&&<Badge tone="danger"><AlertTriangleIcon/> حساسية: {patient.medical.allergies}</Badge>}</div><p>{patient.fileNo} · {patient.phone||'بدون رقم هاتف'} · {patient.email||'بدون بريد إلكتروني'}</p><div className="profile-actions"><Link to={`${prefix}/appointments/new`} className="mini-action"><CalendarPlus size={15}/> حجز موعد</Link>{user.role!=='patient'&&<Link to={`${prefix}/labs/new`} className="mini-action"><FlaskConical size={15}/> طلب تحليل</Link>}<Link to={`${prefix}/prescriptions/new?patient=${patient.id}`} className="mini-action"><FileText size={15}/> روشتة جديدة</Link></div></div><div className="profile-badge"><span className="profile-badge-icon"><HeartPulse size={20}/></span><small>ملف طبي</small><b>{patient.status==='active'?'نشط':'مؤرشف'}</b></div></Card>
 <div className="profile-tabs">{tabs.map(([k,label])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{label}{k==='history'&&<small>{timeline.length}</small>}</button>)}</div>
 {tab==='overview'&&<div className="patient-overview-grid"><Card className="medical-card"><div className="card-heading"><div><h2>البيانات الطبية</h2><p>الحساسية والحالات الصحية الحالية</p></div>{user.role!=='receptionist'&&<Button variant="outline" size="sm" onClick={()=>editing?saveMedical():setEditing(true)}>{editing?'حفظ':'تعديل'}</Button>}</div>{editing?<div className="medical-edit-grid"><Field label="الحساسية"><Textarea rows={2} value={medical.allergies||''} onChange={e=>setMedical(v=>({...v,allergies:e.target.value}))}/></Field><Field label="الأمراض المزمنة"><Textarea rows={2} value={medical.chronicConditions||''} onChange={e=>setMedical(v=>({...v,chronicConditions:e.target.value}))}/></Field><Field label="الأدوية الحالية"><Textarea rows={2} value={medical.currentMedications||''} onChange={e=>setMedical(v=>({...v,currentMedications:e.target.value}))}/></Field></div>:<div className="medical-items"><MedicalItem label="الحساسية" value={patient.medical?.allergies||'لا توجد حساسية مسجلة'} tone={patient.medical?.allergyFlag?'danger':'neutral'}/><MedicalItem label="الأمراض المزمنة" value={patient.medical?.chronicConditions||'لا توجد حالات مزمنة مسجلة'}/><MedicalItem label="الأدوية الحالية" value={patient.medical?.currentMedications||'لا توجد أدوية مسجلة'}/></div>}</Card><Card className="timeline-card"><div className="card-heading"><div><h2>آخر الأنشطة</h2><p>آخر تحديثات الملف الطبي</p></div><button className="text-link" onClick={()=>setTab('history')}>عرض الكل <ArrowLeft size={15}/></button></div><Timeline items={timeline.slice(0,5)}/></Card></div>}
 {tab!=='overview'&&<Card className="timeline-card full"><div className="card-heading"><div><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2><p>{list.length} سجل مرتبط بملف المريض</p></div></div><Timeline items={list}/></Card>}
 </div>;
}
function AlertTriangleIcon(){return <Activity size={14}/>}
function MedicalItem({label,value,tone='neutral'}){return <div className={`medical-item ${tone==='danger'?'medical-danger':''}`}><small>{label}</small><b>{value}</b></div>}
function Timeline({items}){const labels={visit:['زيارة طبية',Stethoscope],appointment:['موعد',CalendarDaysIcon],lab:['طلب تحليل',FlaskConical],prescription:['روشتة طبية',FileText],note:['ملاحظة',Edit3]};if(!items.length)return <EmptyState title="لا توجد سجلات في هذا القسم" description="ستظهر السجلات هنا عند إضافتها."/>;return <div className="timeline-list">{items.map((x,i)=>{const [label,Icon]=labels[x.kind]||['نشاط',Activity];return <div key={`${x.kind}-${x.id}`} className="timeline-item"><span className="timeline-line-icon"><Icon size={16}/></span><div className="timeline-content"><div className="timeline-title"><b>{label} {x.type?`· ${typeText[x.type]||x.type}`:''}</b><small>{formatDate(x.created_at||x.start_at||x.ordered_at||x.issued_at,true)}</small></div><p>{x.diagnosis||x.reason||x.title||x.body||x.status||x.complaint||'تحديث في الملف الطبي'}</p><div className="timeline-meta">{x.status&&<StatusBadge status={x.status}/>}</div></div></div>})}</div>}
function CalendarDaysIcon(){return <CalendarCheck2 size={16}/>}
